bosun-monitor/bosun

- cmd/bosun/sched/template.go
Three arguments as strings, url, content-type (i.e. application/json), and the post data
> Add HTTP Post template func

- cmd/scollector/collectors/sql_windows.go
- cmd/scollector/collectors/wmi_windows.go
Also convert destination to lowercase so it matches host values.
> cmd/scollector: Add mssql.replica.votes and cluster_state.

- cmd/bosun/expr/funcs.go
note we moved the common logic into parseGraphiteResponse
> add graphiteBand function

- cmd/scollector/collectors/processes_windows.go
Quick fix while pending implementation of https://github.com/bosun-monitor/bosun/issues/575
> cmd/scollector: Add additional services to win.proc monitoring

- cmd/scollector/collectors/exim_linux.go
Did not handle case where size was zero or less than 1KB
> cmd/scollector: Fix issue with exim collector

- cmd/bosun/expr/funcs.go
Useful for when you want to join on a tag key, but the tag key from one underlying series does not match the tag key of the other.
> cmd/bosun: Add rename func to rename tag keys

- cmd/scollector/collectors/puppet_linux.go
Also set a metric if puppet is disabled for "reason not specified"
> cmd/scollector: Send puppet disabled reason as metadata

- cmd/scollector/main.go
Fixes #509 which was also asked for in #695
> cmd/scollector: Make the default frequency setable

- cmd/scollector/collectors/vsphere.go
Fixes issue with multiple service tags on new VM servers (see ny-bosun01 logs)
> cmd/scollector: fix multiple service tags for blade servers in vsphere

- cmd/bosun/sched/notify.go
Making sure to queue next notification instead of requeueing same one again
> Properly chain notifications.

- cmd/scollector/collectors/snmp_cisco.go
> Duplicating cisco.cpu to os.cpu

- cmd/scollector/main.go
> quiting with error on bad filter

- cmd/bosun/conf/conf.go
also gave the old lookup function a new name to clearly distinguish the two.
> add lookup function that leverages tags in given series

- cmd/scollector/collectors/puppet_linux.go
> Add timing metrics to puppet-run.

- cmd/bosun/sched/template.go
via documentation and more suitable variable naming
> make it clearer how LeftJoin works

- cmd/scollector/main.go
- collect/collect.go
> #594 - scollector metrics don't honor hostname

- cmd/bosun/expr/funcs.go
This pull request adds des(), a function for smoothing time series using Holt-Winters double exponential smoothing. I'll create a corresponding pull request for documentation soon.
> Add double exponential smoothing function Des()

- cmd/bosun/sched/check_test.go
- cmd/bosun/sched/notify.go
> cmd/bosun: Fix silence logic

- cmd/bosun/main.go
- cmd/bosun/syslog_unix.go
> cmd/bosun: log to syslog

- cmd/bosun/syslog_unix.go
> bosun: Set default log level of INFO for syslog_unix.

- cmd/scollector/collectors/dotnet_windows.go
- cmd/scollector/collectors/processes_windows.go
Also cleanup default process and process_dotnet settings.
This is currently running as a second instance on ny-web01 pointed at devbosun
> cmd/scollector: win.service.* metrics

- _third_party/code.google.com/p/winsvc/eventlog/install.go
- _third_party/code.google.com/p/winsvc/registry/registry.go
- cmd/scollector/service_windows.go
See http://stackoverflow.com/questions/29130586
This will update the EventMessageFile to have the correct value when installing or running the service
> cmd/scollector: fix for "The description for Event ID" in event logs

- cmd/bosun/sched/check.go
- cmd/bosun/sched/sched_test.go
This should fix the case where graphite or opentsdb go down, and unknown alerts pop up in addition to errors. 
If there is an error on an alert, don't create new unknown events.
Also fixes what happens when errors resolve. On first non-error status, it will generate a normal event for the empty tagset for the alert. 
Will not generate unknown events for currently Errored alert keys.
> Error behaviour

- cmd/bosun/conf/conf.go
- cmd/bosun/conf/dependencies_test.go
> Loading notifications referenced by notification lookup

- cmd/scollector/collectors/chef_linux.go
Simple collector for Chef, reads and parses last line from `/var/chef/reports/run_status_json.log`.
> cmd/scollector: Chef collector

- cmd/scollector/collectors/redis_unix.go
And again I forgot to commit before push. [Previous try] (https://github.com/bosun-monitor/bosun/pull/816)
Changed if logic as @mjibson advised.
>   cmd/scollector: commandstats metrics for redis #3

- cmd/bosun/expr/funcs.go
Add a missing function to Bosun. I plan to send a PR updating the docs for DropGe and DropLe (which is missing documentation) soon
> Implement function DropGe, to complement the already implemented DropLe

- cmd/bosun/sched/sched.go
> Instrumenting state file size.

- cmd/bosun/conf/conf.go
- cmd/bosun/conf/notify.go
> Adding configuration option to set content-type on post notification.

- cmd/bosun/web/static/js/bosun.js
- cmd/bosun/web/static/js/state.ts
> Allowing errors to be closed in bulk.

- cmd/scollector/collectors/apache_mod_info_linux.go
- cmd/scollector/collectors/interval.go
> cmd/scollector: use a regex to check for apache info

- mk_rpm_fpmdir.tsdbrelay.txt
:eyeglasses:  @kylebrandt  @captncraig
> Add fpm config for tsdbrelay.

- _third_party/github.com/facebookgo/httpcontrol/example_test.go
- _third_party/github.com/facebookgo/httpcontrol/httpcontrol.go
- _third_party/github.com/facebookgo/httpcontrol/httpcontrol_test.go
- _third_party/github.com/facebookgo/httpcontrol/license
- _third_party/github.com/facebookgo/httpcontrol/patents
- _third_party/github.com/facebookgo/httpcontrol/readme.md
- _third_party/github.com/facebookgo/pqueue/license
- _third_party/github.com/facebookgo/pqueue/pqueue.go
- _third_party/github.com/facebookgo/pqueue/pqueue_test.go
- _third_party/github.com/facebookgo/pqueue/readme.md
- cmd/bosun/main.go
> cmd/bosun: use httpcontrol to retry bad HTTP requests

- graphite/graphite.go
as discussed with @mjibson 
grafana alerting needs this
> support graphite context with custom header

- cmd/scollector/doc.go
> cmd/scollector: update SNMP docs; doc cleanup

- graphite/graphite.go
> graphite: support HTTPS hosts

- cmd/bosun/expr/funcs.go
Previously epoch, since, and forcastlr would use time.Now.
fixes #789
> cmd/bosun: always use State instead of current time

- cmd/bosun/sched/bolt.go
- cmd/bosun/sched/check.go
- cmd/bosun/sched/check_test.go
- cmd/bosun/sched/sched.go
This needs to be added to fix historic incidents after merging previous pr.
> Actually adding historic incidents to global map.

- cmd/bosun/sched/check_test.go
- cmd/bosun/sched/notify.go
> cmd/bosun: add a default unknownTemplate

- cmd/bosun/expr/expr.go
- cmd/bosun/expr/expr_test.go
- cmd/bosun/web/static.go
This also corrects the handling of NaN so it can short circuit.
> Short circuit || and &&

- _third_party/github.com/BurntSushi/toml/COMPATIBLE
- _third_party/github.com/BurntSushi/toml/COPYING
- _third_party/github.com/BurntSushi/toml/Makefile
- _third_party/github.com/BurntSushi/toml/README.md
- _third_party/github.com/BurntSushi/toml/decode.go
- _third_party/github.com/BurntSushi/toml/decode_meta.go
- _third_party/github.com/BurntSushi/toml/decode_test.go
- _third_party/github.com/BurntSushi/toml/doc.go
- _third_party/github.com/BurntSushi/toml/encode.go
- _third_party/github.com/BurntSushi/toml/encode_test.go
- _third_party/github.com/BurntSushi/toml/encoding_types.go
- _third_party/github.com/BurntSushi/toml/encoding_types_1.1.go
- _third_party/github.com/BurntSushi/toml/lex.go
- _third_party/github.com/BurntSushi/toml/parse.go
- _third_party/github.com/BurntSushi/toml/session.vim
- _third_party/github.com/BurntSushi/toml/type_check.go
- _third_party/github.com/BurntSushi/toml/type_fields.go
- cmd/scollector/collectors/aws.go
- cmd/scollector/collectors/collectors.go
- cmd/scollector/collectors/haproxy_unix.go
- cmd/scollector/collectors/icmp.go
- cmd/scollector/collectors/keepalived_linux.go
- cmd/scollector/collectors/processes_linux.go
- cmd/scollector/collectors/processes_windows.go
- cmd/scollector/collectors/snmp.go
- cmd/scollector/collectors/vsphere.go
- cmd/scollector/main.go
> cmd/scollector: move to TOML conf file

- docs/_config.yml
- docs/_layouts/default.html
- docs/downloads.md
- docs/scollector/index.html
Removes need for hard coded version in config.yml
> Using github metadata for latest release in documentation

- cmd/bosun/main.go
> cmd/bosun: use proxy from environment variables

- cmd/scollector/collectors/collectors.go
- cmd/scollector/collectors/httpunit.go
see https://github.com/bosun-monitor/bosun/pull/1052
> cmd/scollector: convert bools to 1/0

- docs/api.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1060)
> docs: fix /api/config_test; document /api/backup

- cmd/scollector/doc.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1073)
> docs: Fix config file name

- cmd/scollector/collectors/wmi_windows.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1078)
> cmd/scollector: don't use time var just for an error return

- build/build.go
- version/version.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1081)
> Build improvements

- build.scollector.sh
- build/build.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1082)
> Build package sh

- cmd/scollector/collectors/collectors.go
- cmd/scollector/collectors/snmp_ifaces.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1090)
> cmd/scollector: implement os.net.pause_frames

- docs/configuration.md
- graphite/graphite.go
@woodsaj looks good to you?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1091)
> Graphite custom path

- cmd/scollector/main.go
fixes #1085
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1086)
> cmd/scollector: fix ICMP TOML converter

- docs/scollector/index.html
> docs: fix scollector arm download links

- docs/expressions.md
updated from #1119, squashed into a single commit.
> docs: expression language doc edits

- cmd/bosun/sched/sched.go
- cmd/scollector/conf/conf.go
- cmd/scollector/doc.go
- cmd/scollector/main.go
- collect/collect.go
and add BatchSize option to toml file
> cmd/scollector: Increase default batch size to 500

- cmd/bosun/sched/sched.go
bug in previous pr stopped these stats from working.
> bosun: Fixing lock metric names

- cmd/bosun/sched/silence.go
Should reduce total number of loops dramatically.
> bosun: Fix slowness loading dashboard.

- collect/collect.go
- collect/queue.go
Also zero out some post metrics on start to prevent them from going unknown.
> collect: Add total_bytes and sample batchsize. Fixes #1184

- cmd/bosun/sched/bolt.go
- cmd/bosun/sched/sched.go
Previously save didn't cause problems because it did so entirely unlocked. I am surprised we haven't corrupted our state file by now. Just gotta try to keep time in lock to minimum, so increasing throttle time to 10sec.
> bosun: Reducing time spent locked during save.

- cmd/scollector/collectors/riak.go
- cmd/scollector/conf/conf.go
- cmd/scollector/doc.go
- cmd/scollector/main.go
Allow to specify custom URL for Riak collector.
> cmd/scollector: riak allow custom URL

- cmd/bosun/sched/template.go
> cmd/bosun: recovering from panic in chart rendering.

- cmd/scollector/collectors/snmp.go
- cmd/scollector/collectors/snmp_cisco.go
- cmd/snmpTester/main.go
- cmd/snmpTester/static.go
- cmd/snmpTester/static/index.html
simple little web app to test snmp configs and oids and stuff outside of scollector. Not sure best way to deploy it. I can think of a few options:
- standalond app in cmd.
- hidden in bosun, since we already have web stuff there.
- Run from scollector as a special mode. 
This should be useful for anyone working on adding new snmp interfaces to scollector.
> Snmp tester

- cmd/scollector/collectors/collectors.go
- cmd/scollector/collectors/github.go
- cmd/scollector/collectors/haproxy_unix.go
- cmd/scollector/conf/conf.go
- cmd/scollector/main.go
Collector that reports open issue count and open pr count.
Also working out new initialization procedure so collectors can register their own callbacks to occur after config parsing. This should simplify main.go as individual collectors are able to call their own setup functions.
> scollector: github collector

- cmd/scollector/collectors/metadata_linux.go
Check for /etc/os-release first, and then fall back to /etc/issue
> cmd/scollector: Get OS Version in CentOS 7

- cmd/scollector/collectors/disk_linux.go
fixes #1286 
> If a filesystem is marked with "nodev", this means that it does not require a block device to be mounted (e.g., virtual filesystem, network filesystem).
> - man proc 5
> cmd/scollector: dfstat skip pseudo filesystems

- cmd/bosun/sched/bolt.go
> bosun: Fixing panic if bucket does not exist for restoreState

- cmd/scollector/main.go
> cmd/scollector: Setup a fake url when the -p option is given

- cmd/bosun/database/database.go
- cmd/bosun/database/search_data.go
- cmd/bosun/database/test/search_data_test.go
- cmd/bosun/sched/sched_test.go
- cmd/bosun/search/search.go
- cmd/bosun/search/search_test.go
- cmd/bosun/web/search.go
- cmd/bosun/web/web.go
> bosun: search keeps set of all metric/tagsets

- cmd/scollector/collectors/collectors.go
Key the interfaces by the name instead of index. Also collect IP addresses as a JSON array.
> cmd/scollector: Linux interface metadata changes

- cmd/scollector/collectors/collectors.go
- cmd/scollector/collectors/snmp.go
- cmd/scollector/collectors/snmp_ips.go
Don't remove CIDR network from IP Address string and poll IFMIB ip address entries
> cmd/scollector: Get Ip Addresses and subnet mask in linux+snmp

- cmd/tsdbrelay/integrationTest/main.go
- cmd/tsdbrelay/main.go
were a few bugs that I didn't catch. And its tested now.
> cmd/tsdbrelay: fixing  tsdbrelay for metadata

- docs/configuration.md
Just add missing info to the docs
> Document variables available for templates referent to incidents

- cmd/bosun/sched/host.go
also remove uncleaned debug message
> cmd/bosun: Add services and their running state to host API

- cmd/scollector/collectors/google_analytics.go
Resulting errors look like the following:
```
2015/11/03 23:33:54 info: queue.go:65: sending: 10, remaining: 0
2015/11/03 23:33:54 info: queue.go:130: sent 10
2015/11/03 23:33:57 error: interval.go:62: c_google_analytics: 
googleapi: Error 403: Daily Limit Exceeded, dailyLimitExceeded
googleapi: Error 403: Daily Limit Exceeded, dailyLimitExceeded
googleapi: Error 403: Daily Limit Exceeded, dailyLimitExceeded
googleapi: Error 403: Daily Limit Exceeded, dailyLimitExceeded
googleapi: Error 403: Daily Limit Exceeded, dailyLimitExceeded
2015/11/03 23:33:57 info: queue.go:65: sending: 2, remaining: 0
2015/11/03 23:33:57 info: queue.go:130: sent 2
```
Can go with a non-newline style if desired, but we will get very-long-lines in that case.
:eyeglasses: @kylebrandt @captncraig
> c_google_analytics: Actually gather GA errors.

- cmd/scollector/collectors/puppet_linux.go
:eyeglasses: @captncraig @gbrayut
> puppet_linux: Track number of seconds since puppet last ran.

- cmd/bosun/conf/notify.go
> Logging on post notifications.

- cmd/scollector/collectors/nexpose.go
Will allow us to compare risk scores for different asset groups.
:eyeglasses: @captncraig @kylebrandt
> c_nexpose: Gather data on asset groups.

- cmd/bosun/sched/bolt.go
- cmd/bosun/sched/notify.go
> cmd/bosun: fixing bug with chained notifications.

- cmd/bosun/database/config_data.go
- cmd/bosun/database/database.go
- cmd/bosun/database/notification_data.go
- cmd/bosun/database/search_data.go
- cmd/bosun/database/test/notifications_test.go
- cmd/bosun/database/test/search_data_test.go
- cmd/bosun/sched/alertRunner.go
- cmd/bosun/sched/bolt.go
- cmd/bosun/sched/check.go
- cmd/bosun/sched/check_test.go
- cmd/bosun/sched/host.go
- cmd/bosun/sched/notify.go
- cmd/bosun/sched/sched.go
- cmd/bosun/sched/silence.go
- cmd/bosun/web/expr.go
- cmd/bosun/web/web.go
> cmd/bosun: optimizing redis access to get tag sets

- cmd/bosun/database/state_data.go
- cmd/bosun/sched/check.go
- cmd/bosun/sched/sched.go
I thought I merged this already
> cmd/bosun: performing a preliminary save on new incidents to keep templates consistent

- cmd/bosun/database/config_data.go
- cmd/bosun/database/test/config_test.go
> cmd/bosun: fixing ledis error saving temp config.

- cmd/bosun/web/web.go
> cmd/bosun: don't panic on opentsdb version

- cmd/bosun/conf/conf.go
- cmd/bosun/sched/sched.go
This will allow multiple instances to run on a single host.
Not sure I understood everything written in the CONTRIBUTING.md file(not a Go dev) but it did seem to pass the build/validate.sh script and it's fairly simple.
> cmd/bosun/(conf|sched) add Ledis bind address config option

- cmd/bosun/conf/conf.go
- docs/configuration.md
This allows one to have variables in alerts that contain html (such as links)
> Add html function to templates

- cmd/bosun/expr/funcs_test.go
- docs/README.md
- docs/expressions.md
This adds some basic units and docs for the timedelta expression.
> timedelta docs and units

- cmd/bosun/expr/funcs.go
- cmd/bosun/expr/funcs_test.go
- docs/README.md
- docs/expressions.md
Needs docs, and a couple funcs_test.go would be nice
> cmd/bosun: add timedelta func

- cmd/bosun/expr/funcs.go
- docs/expressions.md
fixes #1701 Also move rename to proper section in documentation
> cmd/bosun: Add addtags function

- cmd/bosun/expr/funcs.go
- docs/expressions.md
fixes #1773 (Year of the Boston Tea Party)
> cmd/bosun: add crop function

- cmd/scollector/collectors/collectors_test.go
- cmd/scollector/collectors/disk.go
- cmd/scollector/collectors/disk_linux.go
- cmd/scollector/collectors/disk_linux_test.go
- cmd/scollector/collectors/disk_test.go
- Use IsDigit() instead of own function.
- Get status of each spindle.
- Added tests that are not linux specific.
> Added raid mdadm status collector.

- cmd/scollector/collectors/google_analytics.go
This is to prevent the crazy long tail we have on this metric. It's generating thousands of tags.
:eyeglasses: @kylebrandt / @gbrayut
> cmd/scollector: google_analytics: Limit the number of sources we record.

- cmd/scollector/collectors/extrahop.go
- cmd/scollector/conf/conf.go
- cmd/scollector/doc.go
- cmd/scollector/main.go
- vendor/github.com/kylebrandt/gohop/gohop.go
- vendor/vendor.json
Added functionality into the ExtraHop collector for collecting information about SSL certificates seen on the wire.
> cmd/scollector: Added SSL collectors into extrahop collector

- vendor/github.com/StackExchange/wmi/wmi.go
- vendor/vendor.json
see https://github.com/StackExchange/wmi/pull/16
> scollector: update wmi package

- vendor/github.com/StackExchange/wmi/wmi.go
- vendor/vendor.json
vendor: switch to COINIT_APARTMENTTHREADED, fix memory leak in wmi and add float32 support
see https://github.com/StackExchange/wmi/pull/13#issuecomment-236032373
> scollector: update wmi package take two

- vendor/github.com/godbus/dbus/conn.go
- vendor/github.com/godbus/dbus/conn_other.go
- vendor/github.com/godbus/dbus/dbus.go
- vendor/github.com/godbus/dbus/export.go
- vendor/github.com/godbus/dbus/message.go
- vendor/github.com/godbus/dbus/transport_tcp.go
- vendor/github.com/godbus/dbus/transport_unixcred_openbsd.go
- vendor/vendor.json
Updated to 7a8c533d28e8162671a81090af5b9f78b74e2d26
fixes #1854
> vendor: update vendor/github.com/godbus/dbus

- cmd/silence/main.go
> cmd/silence: allow empty tag sets

- cmd/bosun/main.go
- cmd/bosun/ping/ping.go
- cmd/bosun/sched/alertRunner.go
- cmd/bosun/sched/sched.go
> cmd/bosun: move ping out of sched

- collect/queue.go
Adding a null check on error to prevent unexpected exit.
> Collect: Add null check on error

- cmd/bosun/expr/expr.go
- cmd/bosun/expr/funcs.go
- docs/expressions.md
- models/incidents.go
Mainly meant to be used for Grafana, possible WIP... or maybe fine as is... would at least need tests and docs
> cmd/bosun: POC for table type with leftjoin func

- cmd/bosun/expr/elastic.go
This makes it so queries still work regardless of the particular datetime mapping in elastic
> cmd/bosun: specify time format in query

- cmd/bosun/docker/build/Dockerfile
- cmd/bosun/docker/docker.sh
- cmd/bosun/docker/run/Dockerfile
- cmd/bosun/docker/run/bosun.conf
- cmd/bosun/docker/run/bosun.toml
- cmd/bosun/docker/run/bosunrules.conf
- cmd/bosun/docker/run/supervisord.conf
- cmd/bosun/main.go
This uses the new TOML configuration format and allows the rules to be reloaded from the UI.
Also update HBASE to latest release and set explicit version for OpenTSDB git clone
> cmd/bosun: update docker container to 0.6.0-pre version

- opentsdb/tsdb.go
:eyeglasses:  @captncraig / @kylebrandt
> Add delete field to opentsdb.Request.

- cmd/bosun/sched/alertRunner.go
- cmd/bosun/sched/sched_test.go
> Letting scheduler trigger alerts from central place.

- cmd/bosun/conf/rule/rule.go
- cmd/bosun/conf/rule/rule_test.go
> cmd/bosun: fix rule validation around notifications

- 0.6.0.draftnotes.md
> Extremely minor changes

- docs/resources.md
Added the information for the SCollector Puppet module to resources.md.
> SCollector Puppet Module

- docs/definitions.md
- docs/system_configuration.md
As discussed with @kylebrandt in Slack. :)
> Various config doc patches

- cmd/scollector/collectors/haproxy_unix.go
> cmd/scollector: issue #2112 added more haproxy metrics

- cmd/scollector/collectors/hbase_unix.go
This change adds collection of per-region metrics from hbase with tags for namespace, region and table.
> Add per-region details to hbase collector

- cmd/scollector/collectors/processes_linux.go
> Pop the free ID when assigning to a process

- cmd/bosun/expr/influx.go
> Fix influxdb query caching

- cmd/scollector/collectors/procstats_linux.go
MemAvailable was introduced in the 3.14 kernel and is a more accurate measure of available memory
we use that metric if it is available on the system
> scollector: more accurate linux mem free if available

- cmd/bosun/conf/rule/rule.go
- cmd/bosun/expr/annotate.go
- cmd/bosun/expr/azure.go
- cmd/bosun/expr/elastic2.go
- cmd/bosun/expr/elastic5.go
- cmd/bosun/expr/expr.go
- cmd/bosun/expr/funcs.go
- cmd/bosun/expr/graphite.go
- cmd/bosun/expr/influx.go
- cmd/bosun/expr/influx_test.go
- cmd/bosun/expr/tsdb.go
this gets rid of lot arguments around the code
> cmd/bosun: move miniprofiler Timer to state

- cmd/bosun/sched/template.go
- docs/definitions.md
adds context-bound .AzureResourceTags template function
> cmd/bosun: add template func to get azure resource tags

- cmd/bosun/database/database.go
- cmd/bosun/database/migrate.go
this should have been done as part of the inital migration commit. #2335
> cmd/bosun: bump db schema version

- cmd/bosun/expr/funcs.go
Hi! We've caught 2 panics of bosun related with some combination of incoming data from graphite and rules of alerting.
```
error: expr.go:142: Error: interface conversion: expr.Value is expr.Number, not expr.Series. Origin: Schedule: Alert Name: nettools_memory. Expression: max(max(graphite("aliasByNode(movingAverage(sys.hostname*.memory.MemTotal, 4), 1)", "20m", "5m", "host") - graphite("aliasByNode(movingAverage(sys.{netshell,netmon,nettools}.memory.MemFree, 4), 1)", "20m", "5m", "host") + graphite("aliasByNode(movingAverage(sys.hostname*.memory.Cached, 4), 1)", "20m", "5m", "host")) / graphite("aliasByNode(movingAverage(sys.hostname*.memory.MemTotal, 4), 1)", "20m", "5m", "host") * 100) > 90.0, Stack: goroutine 496765 [running]:  
...
/usr/lib64/go/src/runtime/panic.go:513 +0x1b9 …
```
> Fix crashing in Limit and reduce functions

- cmd/bosun/conf/conf.go
- cmd/bosun/conf/system.go
- cmd/bosun/conf/system_test.go
- cmd/bosun/main.go
- docs/system_configuration.md
Small patch that adding [Netflix dynomite](https://github.com/Netflix/dynomite) as HA Redis backend to Bosun.
> Add Netflix/dynomite support

- cmd/bosun/sched/check.go
- cmd/bosun/web/chart.go
make sure backend is initialized in all places
> cmd/bosun: fix prom on rule editor

- cmd/bosun/expr/funcs.go
```
$a = series("host=foo", 0, 1)
$b = series("host=bar", 0, 1)
$c = series("host=baz", 0, 1)
$sA = merge($a, $b)
$sB = merge($a, $c)
$operation = avg($sA) + avg($sB)
$isNan = isnan($operation)
filter($operation, $isNan))
```
> cmd/bosun: (wip) isnan func

- cmd/bosun/expr/prom.go
- docs/expressions.md
> Minor fixes for prom(m)ras

- cmd/bosun/database/silence_data.go
```
2019/02/08 12:00:22 error: silence.go:20: Error fetching silences.unexpected end of JSON input
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf4cc4b]
goroutine 38005 [running]:
bosun.org/cmd/bosun/sched.(*Schedule).CheckNotifications(0x2061760, 0x0, 0x0, 0x0)
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/sched/notify.go:68 +0x1cb
bosun.org/cmd/bosun/sched.(*Schedule).dispatchNotifications(0x2061760)
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/sched/notify.go:28 +0x1c0
created by bosun.org/cmd/bosun/sched.(*Schedule).Run
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/sched/alertRunner.go:18 +0xa4
```
Key 5de2a7387b084908234906b89e522b7dcd6e8afc exists in …
> Fix crashing if incorrect data within Silence

- cmd/bosun/web/web.go
Fix crashing while query /api/status
> Fix for issue https://github.com/bosun-monitor/bosun/issues/2421

- docs/index.md
Remove the deprecation notice and update with announcement of new maintainers
> Remove the deprecation notice

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Adds contributing guidelines for the Bosun project.
> Add contributing guidelines

- cmd/bosun/docker/build/Dockerfile
- cmd/bosun/docker/run/Dockerfile
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like
---
Update go version to 13, which includes go modules by default.
Also upgrade Debian version from Wheezy to Stretch and update corresponding jdks since Wheezy has been [removed from mirror network](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html), which meant docker builds failed with 404s.
Can't update to Buster because it requires jdk-11, which [removes Java EE modules](https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#JDK-8190378) which OpenTSDB relies on.
Fixes #0000 (fill in)
From the …
> Update dockerfiles following go modules update

- docs/api.md
Removes the documentation for /api/templates from the documentation. The
endpoint was removed in 6fc1bfc.
Resolves #2361
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like
---
Please describe your contribution in an issue first, to see if it fits the roadmap of the project. This makes it easier 
for us and you to accept your contribution without requiring too much rework.
Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
Fixes #2361 
From the following, please check the …
> Remove /api/templates from documentation

- cmd/bosun/sched/alertRunner.go
- cmd/bosun/sched/notify.go
Fixes #2444 
The test is described in issue #2444
> Fix duplication of chained notifications while reload config through api

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- Makefile
- build/syncTokens/main.go
- build/test-startup.sh
- cmd/bosun/database/error_data.go
- cmd/bosun/database/metric_metadata.go
- cmd/bosun/database/test/config_test.go
- cmd/bosun/sched/check_test.go
- cmd/bosun/search/search_test.go
- cmd/bosun/web/relay_test.go
- cmd/scollector/collectors/collectors_test.go
- cmd/scollector/collectors/ntp_unix.go
- cmd/scollector/collectors/processes_darwin.go
- cmd/silence/main.go
- collect/collect.go
- host/host.go
- host/host_test.go
- host/name.go
- opentsdb/name.go
- opentsdb/name_test.go
- opentsdb/tsdb.go
- package-lock.json
- package.json
Adds a Github actions pipeline that builds the binaries, runs all tests and checks. This can eventually replace Travis or some parts that are run in its pipeline.
Also adds a check that all source files have been formatted with `goimports`. This explains the reordering of imports in this PR.
> Add Github actions

- .github/workflows/ci.yaml
- .github/workflows/sonarcloud.yml
- Makefile
- sonar-project.properties
- Fixes the Github CI action to build all packages. The previous version only built the Bosun binary, but that doesn't include all packages in this repository. To see that this project builds correctly, we need to build all packages explicitly.
- Installs all dependencies (most notably, Typescript) required by the SonarCloud step.
- Specifies the path to the report files explicitly so that SonarCloud can use them.
> Fix Github Actions

- cmd/bosun/expr/parse/node.go
- cmd/scollector/collectors/processes_linux.go
---
Remove unneeded string() cast that now triggers vet check in go 1.15
> Style fixes for 1.15 compatibility

- docker/opentsdb.Dockerfile
---
Updates the OpenTSDB Dockerfile to use python 3. Later versions of the
alpine base image need an explicit version of Python specified. The
previous `python` package without a version doesn't exist anymore.
Fixes #2491
> Install Python 3 in Docker image

- graphite/graphite.go
- graphite/graphite_test.go
---
Fixes panic when an IP address without a scheme was used as the graphite host.
E.g.
```
[GraphiteConf]
Host = "127.0.0.1:80"
```
Results in 
```
2020/06/30 17:45:29 enabling syslog
2020/06/30 17:45:29 info: migrate.go:138: checking migrations
2020/06/30 17:45:29 info: search.go:208: Loading last datapoints from redis
2020/06/30 17:45:29 info: search.go:215: Done
2020/06/30 17:45:29 info: check.go:562: check alert example.graphite start with now set to 2020-06-30 16:45:29.095031
2020/06/30 17:45:29 info: check.go:562: check alert example.opentsdb.os.high.cpu start with now set to 2020-06-30 16:45:29.095031
2020/06/30 17:45:29 info: check.go:562: check alert example.opentsdb.cpu.lookup start with now set to 2020-06-30 16:45:29.095031
<nil>2020/06/30 17:45:29 error: expr.go:148: Error: …
```
> Fix panic when ip address without scheme is used for graphite backend

- docs/index.md
A long overdue update for https://bosun.org/
> Update project status message on bosun.org
