cmd/bosun/docker/run/Dockerfile

Doesn't look like there's any reason to stay on openjdk-6?
http://opentsdb.net/docs/build/html/installation.html#runtime-requirements
https://github.com/dockerfile/java/blob/master/openjdk-7-jdk/Dockerfile

Update to use openjdk-7

---

cmd/bosun/expr/funcs.go

based on whatever the crafted "now" is.
otherwise, with end left to nil,
the graphite query will always query data
until the current, real time.

GraphiteQuery: explicitly set end date

---

cmd/bosun/expr/funcs.go

* remove graphiteBand's own empty check, just use the existing one
* provide more context in empty check
* fix error from parsing being recognized in graphiteBand

better errors for empty resultsets

---

cmd/bosun/conf/notify.go

otherwise the subjects can be unreadable due to
whitespace introduced in templates

clean up extraneous whitespace in email subjects

---

cmd/bosun/sched/sched.go
cmd/bosun/web/static/js/bosun.js
cmd/bosun/web/static/js/graph.ts
cmd/bosun/web/static/partials/graph.html
cmd/bosun/web/web.go

Adds support to the MetadataMetrics API for specifying the metric

cmd/bosun: Show description metadata on graph page

---

cmd/bosun/conf/conf.go
cmd/bosun/main.go

Since Bosun relays OpenTSBD data this allows it to relay some information before startup. Without this we get flooded with unknowns on startup if Bosun has been down for more than checkFrequency.

cmd/bosun: Sleep CheckFrequency before running checks on start

---

cmd/bosun/conf/conf.go
cmd/bosun/expr/expr.go
cmd/bosun/sched/notify.go

This helps limit unknown spam when something goes bad. If there are more than Threshold email groups in a single check run, it will roll the remaining unknown emails into a single email that lists all the groups and their alert instances.

cmd/bosun: Limit unknown emails sent in a single check

---

cmd/bosun/sched/check.go

clearer to see them against each other, and other messages.
it's easier on the eyes.
and also on the brain for people with OCD like myself.
before:
2015/02/10 17:30:51 done checking alert os.cpu.idle.web (5.452389916s): 0 crits, 0 warns
2015/02/10 17:30:51 checking alert s3_buffer
2015/02/10 17:30:52 done checking alert s3_buffer (967.57502ms): 0 crits, 0 warns
2015/02/10 17:30:52 checking alert bi
2015/02/10 17:31:00 checkUnknown
2015/02/10 17:31:05 done checking alert bi (12.668303453s): 0 crits, 0 warns
2015/02/10 17:31:05 checking alert requests_by_country
after
2015/02/10 17:32:04 check alert requests_by_country done (26.833528339s): 0 crits, 0 warns
2015/02/10 17:32:04 check alert os.cpu.idle.web start
2015/02/10 17:32:09 check alert os.cpu.idle.web done (5.092954017s): 0 crits, 0 …

align check start/done messages

---

cmd/bosun/sched/template.go

"now" was higher during execution of body/subject templates.
it should remain the exact same as warn/crit expressions
for consistency and caching.

fix #716 divergence of "now" when executing templates

---

cmd/bosun/expr/expr.go
cmd/bosun/expr/funcs.go

@mjibson @kylebrandt we might want to revisit storing series as map[time.Time]float64.
databases like graphite and influxdb return their data time ordered, and i presume opentsdb and ES do the same.  but we lose the ordering, and in some places (like first and last function) and now also here, it's clunky to have to make up for it.  an array of struct{time.Time, float64} seems like a more suitable datastructure for Series.
do we do exact-key lookups anywhere ? (give me the value at given timestamp), that's something we'd have to implement again (with binary search or so) if we were to move away from maps.

function to get the longest streak of a given value, e.g. 0

---

cmd/bosun/conf/conf.go
cmd/bosun/sched/sched.go

Time can be changed with pingDuration config option which uses the format of Go's time.ParseDuration. 0 means means all hosts regardless of age.

cmd/bosun: Only ping hosts with a host tag timestamp newer than 1d

---

cmd/scollector/collectors/program.go
cmd/scollector/collectors/program_linux.go

This may or may not help external collectors shut down when scollector does.

On linux, spawn processes with pdeathsig

---

_third_party/github.com/golang/groupcache/lru/lru.go
_third_party/github.com/golang/groupcache/lru/lru_test.go
_third_party/github.com/golang/groupcache/singleflight/singleflight.go
_third_party/github.com/golang/groupcache/singleflight/singleflight_test.go
cmd/bosun/cache/cache.go
cmd/bosun/conf/conf.go
cmd/bosun/expr/expr.go
cmd/bosun/expr/funcs.go
cmd/bosun/sched/check.go
cmd/bosun/sched/notify.go
cmd/bosun/sched/template.go
cmd/bosun/web/chart.go
cmd/bosun/web/expr.go
graphite/graphite.go
opentsdb/tsdb.go

* for executing expressions/rules via the web UI, we use
a cache that we retain during the lifetime of bosun
Matt and I decided not to expire the cache at given points (such as
reloading rule page), but I forgot why. ?
the only risk is that if you query your store for data -5m to now
and your store doesn't have the latest points up to date,
and then 5m from now you query -10min to -5m you'll get the same
cached data, including the incomplete last points
* for scheduled alert checking, the cache lifetime is only each
specific run so that different queries of the same
data for different templates are optimized and values reused in
templates are guaranteed to be in sync.
we don't make the lifetime longer to prevent affecting
future queries (perhaps a band() a week
from now which queries …

leverage LRU caching for scheduled checks and expr/rule tests

---

cmd/scollector/collectors/network_windows.go

I found some scollector errors in the Windows log files using Kibana:
The c.Enable variable in c_network_team_windows init function was not being updated correctly, probably due to a closure issue. This caused the collector to become active on or-dc02 and ny-dc05 (and others) and produce errors. Renaming the IntervalCollector variable (so it is not shared/reused) appears to solve the closure issue and stop the errors.
Also the PercentTimeinGC values were overflowing uint32, even though that is what WMI says they are. See http://goo.gl/x6om5l for example of error.
These changes are already running in a test build on a handful of systems pointed at prod bosun.

cmd/scollector: fix issues with c_network_team_windows and NETCLRMemory

---

cmd/bosun/sched/check.go
cmd/bosun/sched/check_test.go

We have been getting lots of notification emails with the status of
normal in them. This was because we were rendering the subject and body
before adding the new abnormal state (as we used to).

cmd/bosun: fix "normal" notifications

---

cmd/bosun/sched/check_test.go
cmd/bosun/sched/notify.go

We recently got 9 empty emails at exactly the same time that 9 unknown
alerts triggered. I thought it might be something with the unknown
template, but this test doesn't yet trigger the bug.

cmd/bosun: add test for unknown notifications

---

cmd/scollector/log_unix.go
slog/slog_unix.go

This is needed so we can properly shunt log messages to the file we want.

Add "tag" parameter to SetSyslog and pass it from scollector.

---

cmd/scollector/doc.go

run `godoc -http=:6060` to start a local godoc server, then browse to http://localhost:6060/pkg/bosun.org/cmd/scollector/ to see the changes. 
Live documentation is at http://godoc.org/bosun.org/cmd/scollector

cmd/scollector: update doc.go documentation

---

cmd/scollector/collectors/riak.go

Took inspiration from memcached collector. Metrics are named similarly to tcollector's riak.py . Tested on docker's guillermo/riak which is 1.4.2 version.

cmd/scollector: new collector - riak

---

cmd/bosun/sched/sched_test.go
opentsdb/tsdb.go

this avoids issues when OpenTSDB is not running on UTC timezone. 
Fixes issue #806

use unix timestamps on tsdb request

---

cmd/scollector/collectors/riak.go

I've made a mistake in riak.go collector, there're `mem_total` and `memory_total` that go into same `riak.memory` metric with `total` tag. `mem_total` should be better described as `riak.memory` tag: `available` to the system.

cmd/scollector: Riak - fix total available memory metric

---

slog/slog_windows.go

our scollector.log.errors logstash alert isn't working for Windows because the event log messages don't include the severity level. This change prepends the severity level to the message so they appear the same as those sent to syslog on Linux.

slog: Include severity when writing to event log in Windows

---

cmd/bosun/conf/conf.go
cmd/bosun/conf/conf_test.go
cmd/bosun/conf/invalid/crit-notification-no-template
cmd/bosun/conf/invalid/log-no-notification
cmd/bosun/conf/test.conf
cmd/bosun/sched/check.go
cmd/bosun/sched/check_test.go
cmd/bosun/sched/sched.go

This prevents alerts from appearing on the dashboard, but allows them to
notify every time they trigger.
Also improve strictness of conf checks for alerts, notifications, and
templates.

cmd/bosun: add alert log feature

---

cmd/bosun/sched/check.go
cmd/bosun/sched/sched_test.go
cmd/bosun/web/expr.go
cmd/bosun/web/web.go

Currently GetOrCreateStatus (only used in the web package) is the only
known place outside of RunHistory where state is mutated. This change moves
things like Touched and Result mutation into RunHistory.
This should prevent the recent panics because now the web package won't
create alert keys that shouldn't exist.

cmd/bosun: move more state mutation into RunHistory

---

cmd/bosun/web/expr.go
cmd/bosun/web/web_test.go

Fixes a recent panic. Correct fix would be to refactor the web package to
use RunHistory, which already handled this correctly.

cmd/bosun: Ensure web instances have their result set

---

cmd/scollector/collectors/haproxy_unix.go
cmd/scollector/main.go
metadata/metadata.go

Much of this code is from @kylebrandt, however I have done despicable things to it under the guise of "finishing" it.
I've modeled much of the multiple-fetch off of processes_linux. The config file will look something like the following:
```
haproxy = username:password
haproxy_instance = 1:http://lb01:7001/haproxy;csv
haproxy_instance = 2:http://lb01:7002/haproxy;csv
```
Splitting the instances up is primarily to improve readability and prevent very long lines.
This original code made some assumptions regarding haproxy layout, and I've furthered piled on more assumptions leading to a very assumptive tower of pancakes. The assumptions are as follows:
1. haproxy stats will always be secured with user/pass HTTP auth.
1. Multiple haproxy instances on one server are tagged as 'tiers', a bit of …

Add HAProxy collector

---

opentsdb/tsdb.go

Adding dash to the metric-name regex

---

cmd/scollector/collectors/riak.go

This PR fixes Riak collector calculation of 'connected_nodes' and 'ring_members'. Also updates descriptions to look more like in Basho documentation.

cmd/scollector: Riak - fix 2 metrics

---

cmd/scollector/collectors/dsc_windows.go

This is a first pass at adding basic DSC metrics to scollector. Right now it is just monitoring the size and last modified time of the configuration files. Next I need to add the WMI data from the MSFT_DSCLocalConfigurationManager, but that requires calling a WMI function, so it may or may not work in go yet. I'd like to merge this first to start getting basic stats.
Currently running on two systems pointed at devbosun. See http://goo.gl/FZB5i0 for example query

cmd/scollector: Add dsc.mof file metrics

---

cmd/scollector/main.go
collect/collect.go
collect/queue.go

I'd also like to add metadata to these metrics but not sure exactly where to do that. I assume they can just use a goroutine to send the metric metadata every hour, or whatever our current design is.

collect: Add os tag to scollector.collect.* metrics

---

cmd/bosun/expr/funcs.go
cmd/bosun/web/static/partials/rule.html
graphite/graphite.go

* make errors clearer in the web ui (shows request url and more information about what went wrong)
* print more details to log. in particular, the response body with graphite stacktrace:
```
2015/04/08 18:10:12 bosun web listening on: :8070
2015/04/08 18:10:12 tsdb host: 
2015/04/08 18:10:18 error: funcs.go:351: graphite: Get(http://graphite/render/?format=json&from=1428271818&target=divideSeries%28stats.gauges.stats_buffer_space_mb.%2A._data_s3%2A%29&until=1428531018) failed: got statuscode 500 INTERNAL SERVER ERROR
===================================================
<body style="background-color: #666666; color: black;">
<center>
<h2 style='font-family: "Arial"'>
<p>Graphite encountered an unexpected error while handling your request.</p>
<p>Please contact your site administrator if the …
```

more useful graphite errors

---

cmd/scollector/collectors/haproxy_unix.go

Also typo'd in haproxy's documentation.

cmd/scollector: Fix typo in check_status mapping.

---

.travis.yml
build/validate.sh
cmd/bosun/web/static.go

This should help alleviate the problem where a local version of esc is older than current. Travis always uses latest.
With this running validate.sh locally should update esc and make sure the output matches.

go get -u for esc

---

cmd/scollector/collectors/haproxy_unix.go

cmd/scollect: Do not reuse haproxy stats connections.

---

cmd/bosun/sched/bolt.go
cmd/bosun/web/web.go

Because bosun maintains a file lock on the state file, a simple solution for backups is for bosun itself to be able to backup its own state file.
A GET request to /api/backup will stream the state file over the web request.
`curl bosunserver/api/backup > mybackup-timestamp.state` is all that is needed.

Providing endpoint to backup state file.

---

cmd/bosun/sched/template.go

`{{.Incident}}` should give link to incident on correct host. `{{.State.Last.IncidentId}}` should give just id.

Function to make incident link available to templates

---

cmd/bosun/sched/sched.go
metadata/metadata.go

This is needed so that go programs using the Metasend type can send a nil
time.

metadata: Make time a pointer

---

cmd/bosun/sched/chart.go
cmd/bosun/sched/template.go
cmd/bosun/web/chart.go
docs/configuration.md

Before:
After:
The new argument to Graph is a list of units for the axis. It is vargs so this isn't breaking change (you can omit the second argument). The "title" has been moved to notes at the bottom of the graph, and moved outside of the svg/png. This means they can be copied and pasted when it comes in an email, and there is no issue with text being cut off.

cmd/bosun: png/svg graph style changes

---

cmd/bosun/conf/conf.go
cmd/bosun/sched/check.go
cmd/bosun/sched/check_test.go
cmd/bosun/sched/sched.go
cmd/bosun/sched/sched_test.go
cmd/bosun/web/web.go
docs/configuration.md

Adds a few config options:
1. Alert level `runEvery` which determines how many intervals between checks on this alert.
2. Global `defaultRunEvery` to determine the default modulo.
With a `defaultRunEvery` of 5 and a `confFrequency = 1m`, each alert will run every 5m unless explicitely set to `runEvery = 1` to run every minute.
Fixes #976

Allow alerts to run on different schedules.

---

docs/index.md
docs/slackInvite.html

This depends on a little script I made on hookscript.com which runs a little go script on a webhook. It keeps our access tokens secret and runs only when needed, using undocumented slack apis to do the magic.

docs: Creating form for auto-inviting to slack

---

cmd/bosun/expr/funcs.go
docs/expressions.md

This way it can be used with the upcoming window function. It was made a query function when only OpenTSDB existed, therefore diff(q(...)) was not needed, but now that there are different types of query functions it is useful as a generic reduction function.

cmd/bosun: Change diff to be a reduction function

---

cmd/bosun/conf/conf.go
cmd/bosun/sched/check.go
cmd/bosun/sched/sched.go
docs/configuration.md

Adds `maxLogFrequency` key to alerts that can control how often notification gets run. Only valid on log alerts. 
Fixes #975

bosun: Ability to throttle log notifications

---

build/dockerRelease.sh
build/release.sh

- determine git SHA automatically
- more explicit variable to trigger bosun build
- allow no GitHub access token that still builds binaries for all archs

build: various improvements

---

cmd/bosun/conf/conf.go
cmd/bosun/expr/expr.go
cmd/bosun/expr/funcs.go
cmd/bosun/expr/logstash.go
cmd/bosun/expr/parse/node.go
cmd/bosun/expr/parse/parse.go
cmd/bosun/expr/parse/parse_test.go
cmd/bosun/sched/template.go
cmd/bosun/web/chart.go
docs/expressions.md

This also includes formally renaming Number to NumberSet to cause less confusion.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1071)

Documenting function parameter types and returns

---

cmd/scollector/collectors/activedirectory_windows.go
cmd/scollector/collectors/wmi_windows.go

This replaces the PS1 script that IT wrote for monitoring AD replication with a built in collector. The old metric names were activedirectory.replication.age and activedirectory.replication.failures, but I had to rename them due to how the WMI classes present the data (all sources for a host, not all destinations).
I have it running as a second instance on devbosun right now. See http://goo.gl/HY4rjr and http://goo.gl/jQIXyB for examples (remove host filter to see or-dc issues due to move)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1074)

cmd/scollector: Replace external AD collector with built in collector

---

cmd/scollector/main.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1080)

cmd/scollector: error on unused toml keys

---

cmd/bosun/conf/conf.go
docs/configuration.md

Also sort functions by name.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1083)

cmd/bosun: add pct template function

---

cmd/backfill/main.go
cmd/tsdbrelay/denormalize/denormalization.go
cmd/tsdbrelay/denormalize/denormalization_test.go
cmd/tsdbrelay/main.go
collect/collect.go
collect/queue.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1076)

tsdbrelay: denormalization backfill app

---

cmd/bosun/expr/logstash.go

Tested '/' functionality as concrete ES index name signaling (without Bosun adding date suffix), works great.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1013)

Concrete ls index name

---

cmd/scollector/collectors/processes_linux.go

Calculate process start time and uptime from file stat data of /proc/<pid> directory.
P.S. Chose this because it's way simpler than querying uptime, `getconf CLK_TCK` , parsing stat and jiffies. There were times when `/proc/<pid>` stat data was modifiable but that's fixed now.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1087)

cmd/scollector: process_linux process start_time and uptime

---

cmd/scollector/collectors/processes_linux.go

Sort processes by creation time so lower ids are assigned to older processes. Also helps preserve process ids in case scollector restarts.
P.S. Could be made a bit more effective, but complicates code more than necessary.

cmd/scollector: Order process identifiers by process creation timestamp.

---

cmd/scollector/collectors/httpunit.go

Was there a reason these weren't set previously?

cmd/scollector: Add descriptions to httpunit metrics hu.*

---

cmd/scollector/collectors/processes_darwin.go
cmd/scollector/collectors/processes_linux.go
cmd/scollector/collectors/processes_solaris.go
cmd/scollector/collectors/processes_windows.go
cmd/scollector/collectors/snmp.go
cmd/scollector/collectors/snmp_cisco.go
cmd/scollector/collectors/snmp_ifaces.go
cmd/scollector/conf/conf.go
cmd/scollector/conf/conf_darwin.go
cmd/scollector/conf/conf_linux.go
cmd/scollector/conf/conf_windows.go
cmd/scollector/doc.go
cmd/scollector/main.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bosun-monitor/bosun/1089)

scollector: More generic SNMP collector

---

cmd/bosun/sched/bolt.go
cmd/bosun/sched/check.go
cmd/bosun/sched/notify.go
cmd/bosun/sched/sched.go
cmd/bosun/sched/silence.go

Here we emit metrics about how long a method spent waiting for a lock, as well as how long it held it.
I suspect the slowness on the dashboard is related to lock contention, and this should help diagnose it.

bosun: Adding instrumentation around schedule lock.

---

cmd/scollector/collectors/interval.go

cmd/scollector: scollector.* metrics disabled properly with DisableSelf

---

collect/collect.go
collect/queue.go

Also updated the AggregateMeta function

collect: Instrument aggregation stats for http post timings

---

cmd/scollector/collectors/collectors.go
cmd/scollector/collectors/dotnet_windows.go
cmd/scollector/main.go

the call to AddProcessDotNetConfig in main.go was removed in the e5235d3a4d818057ada4fd41e414a20416aca0f9 commit (conf->toml) which caused many of our dotnet.* metrics to stop reporting about 20 days ago. 
This PR wires up the AddProcessDotNetConfig method similar to how the AddProcessConfig methos is currently used.

cmd/scollector: fix missing call to AddProcessDotNetConfig

---

docs/configuration.md
docs/expressions.md

docs: Adding missing documentation

---

.travis.yml
cmd/bosun/sched/bolt.go
cmd/bosun/sched/sched.go

Uses a single, buffered channel to signal a save is needed. A single worker goroutine monitors this channel and saves as needed. 
In the case of multiple saves in fast succession, this should reduce lock contention on the schedule lock.

bosun: making save rely on fewer goroutines needing to acquire the lock.

---

quickstart.md

The docker registry docs say to expose port 4242 as well as 8070, and the opentsdb exits without this port exposed.

Expose port 4242 in Quickstart

---

cmd/bosun/sched/bolt.go
cmd/bosun/sched/check.go
cmd/bosun/sched/notify.go
cmd/bosun/sched/sched.go
cmd/bosun/sched/silence.go

Save is now taking too long every 10 seconds in our install, because of the time needed to gob encode everything. 
This reduces the save frequency to once a minute, and removes all of the tricky triggers and just does it in a loop.

making save run on a fixed clock

---

cmd/bosun/sched/template.go

A couple functions were using the current wall clock time and not the schedule's start time.

cmd/bosun: Fix template functions to use the same time as the alert

---

cmd/bosun/conf/conf.go
docs/configuration.md

cmd/bosun: Export time.ParseDuration as ParseDuration to templates

---

cmd/bosun/expr/funcs.go
docs/expressions.md

…esults (false)
This is a breaking change. Fixes #1100

cmd/bosun: Refactor filter expr func to also filter out zero valued results

---

cmd/scollector/collectors/ifstat_linux.go

cmd/scollector: Add additional Linux interfaces

---

cmd/scollector/doc.go

docs: Clarify that scollector supports TLS and HTTP Basic Auth. 

---

docs/quickstart.md

- changes `docker-server:8070` to `docker-server-ip:8070`
- changes `your-docker-server:8070` to `docker-server-ip:8070`

Always refer to docker-server-ip in the same way

---

cmd/bosun/sched/sched.go
cmd/bosun/web/web.go

adds endpoint at `/api/debug/schedlock`
data is simply `{"Process":"","HeldFor":""}` if lock is available, or {"Process":"RunHistory","HeldFor":"9ms"} if lock is currently held.

cmd/bosun: adding debug endpoint to view status of schedule lock.

---

cmd/bosun/sched/bolt.go
cmd/bosun/sched/check.go
cmd/bosun/sched/sched.go
cmd/bosun/sched/silence.go

Two main fixes:
1. Reading silences does not require schedule lock, but a more localized silence lock, which is a RWMutex that should take very few Writes.
2. Schedule now has a `readStatus` that is a copy of the authoritative `status`. This should be copied in full at the end of each `RunHistory`.

bosun: Requiring no schedule lock to render dashboard.

---

cmd/scollector/collectors/snmp_ifaces.go

Instead of string parsing - mostly.

cmd/scollector: Identify the interface type via IF-MIB:ifType

---

docs/configuration.md

logstashElasticHost is not used in code base, only 'logstashElasticHosts'

Change Elasticsearch backend configuration key

---

docs/configuration.md

The original says it uses the same format as `tsdbHost`, but it doesn't work if you just use `host:port`. Looking at the code, bosun passes the value(s) here directly to the elastic library which is expecting a URL. Once I used `http://host:port` I was able to query. The error message given before came directly from the elastic library with a generic error message about there being no hosts available so there was no indication that the configuration format was incorrect.

Update logstashElasticHosts format

---

collect/collect.go

I mostly want to see how upgrading to go 1.5 will affect these statistics, so instrumenting them now.

collect: instrumenting some basic gc stats

---

cmd/scollector/collectors/snmp.go
cmd/scollector/collectors/snmp_ifaces.go

Snmp is horrible. Some trees index keys
```
.8.1
.8.2
.8.3
...
```
Others index them:
```
.8.1.1
.8.1.2
.8.1.3
...
```
Scollector would previously reject trees of the second form if present in a MIB. This patch makes all subtree paths strings and if a multipart key is  found simply converts it to `.1.3` style string.

smd/scollector: Allowing multipart snmp keys in subtrees.

---

cmd/bosun/conf/conf.go
cmd/bosun/conf/notify.go
cmd/bosun/sched/check.go
cmd/bosun/sched/notify.go
cmd/bosun/sched/sched.go
cmd/bosun/sched/template.go
cmd/bosun/web/web.go
cmd/scollector/main.go

Should give more consistent logs, including file names.
Also logging check errors.

Using slog everywhere instead of log.

---

cmd/scollector/collectors/ifstat_linux.go
cmd/scollector/collectors/procstats_linux.go

Currently we monitor bonding which works with CentOS 6, but by default CentOS 7 is using teaming and we want to monitor that as well.

cmd/scollector: Monitoring teams interfaces

---

cmd/bosun/sched/sched.go

Fixes #1156.
The dashboard was showing Actions[0] as the last, but we append to the right. If we only give the dashboard the most recent, everything should work.

bosun: Only giving the dashboard the most recent action.

---

cmd/scollector/main.go

I noticed our scollectors reported different host tags for internal metrics.

cmd/scollector: Propagate FullHost setting

---

cmd/bosun/conf/parse/lex.go
cmd/bosun/conf/test.conf

With regards to the os.diskspace alert, I like to write my exceptions for disks like this:
```
lookup disk_space {
entry host=netlog,disk=/data {
warn_percent_free = 5
crit_percent_free = 0
}
entry host=*,disk=* {
warn_percent_free = 10
crit_percent_free = 0
}
}
```
Currently this gives an error: "unexpected invalid character: / in section declaration", this change should remove the bug.
Thanks,

cmd/Bosun: support / in lookup sections

---

.travis.yml
cmd/bosun/web/static.go
cmd/snmpTester/static.go

The newest version is 1.6-beta, and is quite strict.
I've created a new issue #1306 for fix the actual code.

travis: pin Typescript to version 1.5.3

---

cmd/scollector/collectors/hi.go

This can be used to create an alert for scollector being alive and then used as a dependency.

cmd/scollector: Send a hi metric with a value of 1

---

cmd/scollector/collectors/processes_linux.go
cmd/scollector/conf/conf_linux.go

Kind of fixes #1079 . The goal is to have something to track if there are no running processes matching from [[Process]] entry and not use `since()`.

cmd/scollector: count running linux processes from linux.proc collector

---

util/command.go

- separate start from wait. Process takes as long as it needs to start.
- remove select in favor of time.AfterFunc.

util: reworking how util exec works with timeouts

---

cmd/scollector/doc.go

`MIBs` needs to be a toml "table" (parsed as a go `map[string]interface{}`) instead of a toml "array of tables" (parsed as a go `[]map[string]interface{}`).  Also fix a minor typo.

scollector generic SNMP documentation syntax and typo fix

---

cmd/scollector/collectors/collectors.go
cmd/scollector/collectors/interval.go
cmd/scollector/collectors/program.go
cmd/scollector/main.go
collect/queue.go

On SIGINT scollector will:
1. attempt to stop all running collectors. Any collector in a waiting state will immediately return.
2. Attempt to flush all queued datapoints to opentsdb.
3. Exit no matter what after 5 seconds.

scollector: handle SIGINT for somewhat graceful shutdown

---

cmd/bosun/conf/conf.go
cmd/bosun/expr/expr.go
cmd/bosun/expr/expr_test.go
cmd/bosun/expr/influx.go
cmd/bosun/expr/influx_test.go
cmd/bosun/sched/check.go
cmd/bosun/sched/template.go
cmd/bosun/web/chart.go
cmd/bosun/web/expr.go
docs/configuration.md

Adds configuration so that you can connect to InfluxDB with TLS and/or a username and password.

cmd/bosun: add complete influx cred config, docs: update docs to reflect new config

---

cmd/bosun/dev.sample.conf
cmd/bosun/expr/influx.go
cmd/bosun/expr/influx_test.go
docs/expressions.md

A first throw at fixing the inconsistencies. See bug #1298. I think I've fixed the tests. Fighting with travis now.

cmd/Bosun: enable group by interval in the influx() query

---

graphite/graphite.go

a small patch to resolve #1349

cmd/bosun: Allow to query graphite with Auth informations

---

cmd/scollector/collectors/collectors.go
cmd/scollector/collectors/metadata_windows.go

cmd/scollector: Get Ip Addresses and subnetmask in windows. 

---

cmd/scollector/collectors/hbase_unix.go

This is a quick fixup to get this collector working for us again.
Note that this entire collector needs a revamp, but for now I just want to get our metrics. I'm planning on a revamp later.
:eyeglasses: @gbrayut @captncraig

Fix hbase collector for 1.0.

---

cmd/scollector/collectors/snmp.go
cmd/scollector/collectors/snmp_ciscobgp.go

Add SNMP collector for the gathering of BGP health data from Cisco devices (CISCO-BGP4-MIB).

Add ciscobgp snmp collector

---

cmd/scollector/collectors/google_analytics.go
cmd/scollector/conf/conf.go
metadata/metadata.go

If the 'Detailed' attribute is set to true for a GA site in the configuration, this will track additional realtime metrics.
The `getPageviews` function is unchanged from the original. Was simply cut out of `c_google_analytics`.
The new metrics are named as follows:
`google.analytics.realtime.activeusers.by_${DIMENSION}`
:eyeglasses: @kylebrandt @captncraig

c_google_analytics: Gather realtime metrics for browsers, trafficType, deviceCategory, and OS.

---

opentsdb/tsdb.go

The usage of 'key' was erroneous. Corrected it and added the tag which the value was from.
Also added the metric to the error message when a tag failed to clean.
:eyeglasses: @kylebrandt @captncraig

Add more info to Clean() err message.

---

cmd/scollector/collectors/snmp_bridge.go
cmd/scollector/collectors/snmp_ips.go

The `macs` and `ips` data from snmp don't come in ordered. As a result, metadata gets rewritten whenever their order is changed. This should prevent that.
:eyeglasses:  @gbrayut @captncraig

Sort data to prevent arbitrary metadata changes.

---

_third_party/github.com/golang/glog/LICENSE
_third_party/github.com/golang/glog/README
_third_party/github.com/golang/glog/glog.go
_third_party/github.com/golang/glog/glog_file.go
_third_party/github.com/golang/glog/glog_test.go
_third_party/github.com/google/cadvisor/client/README.md
_third_party/github.com/google/cadvisor/client/client.go
_third_party/github.com/google/cadvisor/client/client_test.go
_third_party/github.com/google/cadvisor/info/v1/container.go
_third_party/github.com/google/cadvisor/info/v1/container_test.go
_third_party/github.com/google/cadvisor/info/v1/machine.go
_third_party/github.com/google/cadvisor/info/v1/metric.go
_third_party/golang.org/x/oauth2/google/appenginevm_hook.go
_third_party/golang.org/x/oauth2/google/jwt.go
_third_party/golang.org/x/oauth2/internal/token.go
_third_party/golang.org/x/oauth2/internal/token_test.go
_third_party/golang.org/x/oauth2/internal/transport.go
cmd/scollector/collectors/cadvisor.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go
metadata/metadata.go

Requesting feedback on some initial work done to add support for collecting metrics from [cadvisor](https://github.com/google/cadvisor). 
Currently this collector will pull all running docker containers through cadvisor and add collect various cpu, memory, fs and network stats, tagging them with the container's ID and name.

cmd/scollector: new cadvisor collector

---

cmd/scollector/collectors/puppet_linux.go

We have a couple hosts successfully 'running' puppet and updating the last_run timestamp, but the run has a status of 'failed'. Adding a metric to track that.
:eyeglasses: @gbrayut @captncraig

puppet_linux: Track puppet.run.status and fix broken error checking logic.

---

cmd/scollector/collectors/processes_linux.go

Had an issue with keepalived where the 3 processes had an identical mtime. Resulted in the metric IDs of said processes hopping around, and then counters getting jacked. This should remedy that.
:eyeglasses: @kylebrandt  @captncraig

processes_linux: Add a tiebreaker if the process creation time is identical.

---

cmd/scollector/collectors/redis_counters.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go
cmd/tsdbrelay/main.go
collect/eventListener.go

This is the base implementation of a udp collector. I put it in the collect package because it is not in a `cmd/*` package and it seemed logical. 
We have a couple of options for deploying it:
1) scollector listens locally, stores things in redis master. Less udp traffic on network.
2) bosun listens. 
3) tsdbrelay listens. I don't like this a ton.
My vote is for 2. Any or all of them can be implemented fairly easily. 
@gbrayut @kylebrandt @bretcope

WIP: new udp listener for sporadic counter events.

---

metadata/metadata.go

Defer close http response body in sendMetadata().
The http response body doesn't get closed after sendMetada() return,
which will cause two goroutines and quite some memory leak every hour.
Scollector on our haproxy boxs got to the internal 500 MiB memory limit and
panic crashed within a week. I analyzed the crash log and graphed memory
usage and goroutine count metrics of scollector, then found out the problem.
Metrics are really great for identifying this kind of problems, and I want to say
a big thank you for your great work building bosun and scollector.

metadata: fix a goroutine and memory leak in sendMetadata()

---

cmd/bosun/sched/check.go
cmd/bosun/sched/check_test.go
cmd/bosun/sched/sched.go

Stopping flapping notifications and empty emails

---

cmd/scollector/collectors/elasticsearch.go
cmd/scollector/main.go

This change refactors much of the collector, and also makes it compatible with ElasticSearch 2.
Notable changes:
* All of the JSON we use has been struct-ified.
* Metric metadata and descriptions have been placed into the struct field tags.
* Metrics which are version-specific have been denoted in field tags, and are conditionally sent based on those tags and what version of Elastic we're hitting.
* Namespaces of the metrics have been rearranged to make more intuitive sense.
* Previously local-node index stats were stuck right on `elastic.`, while cluster-white index stats were stuck in `elastic.indices.`. These have been moved to `elastic.indices.local` and `elastic.indices.cluster`, respectively.
* Health-related stats have been moved into `elastic.health`.
* Previously we had a mix of …

c_elasticsearch: Refactor collector.

---

_third_party/github.com/kylebrandt/gohop/gohop.go
cmd/scollector/collectors/extrahop.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go
cmd/scollector/main.go

ExtraHop collector. Right now it only collects the L7 information (bytes and packets) for all networks, broken by vlan and protocol. In the config file you can choose how you want to filter the data - by traffic count, named protocols, or no filtering.

cmd/scollector: Added ExtraHop collector

---

cmd/scollector/collectors/elasticsearch.go

The cluster index stats are identical across all nodes in the cluster, so it only makes sense to collect them from a single node (in this case, I'm using the master).
Also collecting index counts by status in `elastic.health.index_status_count`. This will allow us to measure index health without tracking each individual index in a separate tag, including indices that are excluded by the filter.
:eyeglasses:  @kylebrandt  @captncraig @gbrayut

Tune elasticsearch collector.

---

cmd/scollector/collectors/keepalived_linux.go

:eyeglasses:  @captncraig  @gbrayut @kylebrandt

c_keepalived: Add new SNMP entry so we work with new keepalived 1.2.19,  and fix off-by-one bug.

---

cmd/scollector/collectors/procstats_linux.go

This makes os.mem.free match how os.mem.percent_free works for linux.
:eyeglasses: @kylebrandt  @gbrayut

cmd/scollector: c_procstats_linux: Add buffered and cached memory usage to os.mem.free.

---

cmd/scollector/collectors/local_listener.go
cmd/scollector/collectors/stream.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go

This adds the local_listener collector, it starts an http server locally and listens for /api/put and /api/metadata/put http requests. It ingest that data and forward it through its usual mechanism, basically acting as a proxy.

cmd/scollector collector: local listener

---

cmd/scollector/collectors/snmp_cisco.go

This merge will create a new function, `c_cisco_asa` which will do ASA-specific checks.  The first metric  is supplied with this merge; it checks the current and max connection count for the ASA in question.

Add new ASA-specific struts and new metric

---

collect/collect.go
collect/queue.go

If you use `Put`, `Add` and friends, `Flush` will not send those data points until after they have been aggregated into the queue. This will force Flush to send everything.

collect: Flush purges internal collections as well.

---

cmd/bosun/dev.sample.conf

Avg call in macro example.influx.os.high.cpu is missing a closing bracket. Added it.

cmd/bosun: Added missing bracket in dev.sample.conf

---

cmd/bosun/sched/check.go
cmd/bosun/sched/notify.go
models/incidents.go

Not even storing email body and email subject if identical to regular. If empty when we want to notify we use the regular body. Will be stored if different.

cmd/bosun: fixing empty email body, and handling absence better

---

cmd/bosun/conf/conf.go
cmd/bosun/main.go
cmd/bosun/web/web.go

This adds shortenProxy as option in bosun.toml to add a proxy only to requests out to googleapis' shortener api. The alternative is making use of the default http client's http.ProxyFromEnvironment but it results in all http calls to use it. That includes calls to OpenTSDB which isn't a something we want.

cmd/bosun: Shorten-only http proxy

---

cmd/scollector/main.go

This fixes scollector complaining about MaxQueueLen smaller than the batchsize when it's unset.

cmd/scollector: Fix for unset MaxQueueLen

---

cmd/bosun/expr/funcs.go
docs/expressions.md

This adds the ability to graph multiple seriesSets in expression graphs, and also graph things like week-over-week.

cmd/bosun: Add over, shift, and merge funcs

---

cmd/bosun/expr/funcs.go
docs/expressions.md

for visualizing a linear regression line

cmd/bosun: Add linelr func

---

cmd/bosun/sched/sched.go

We used to remove open alerts with no corresponding alert in conf when we restored the state file. That is't possible in redis now, so there are a lot of warnings from the dashboard when alerts are left open after the alert is removed from the conf. 
This will force close those so the warnings stop, but will not delete history.

cmd/bosun: Auto-Closing open alerts if alert doesn't exist anymore.

---

cmd/bosun/docker/build/Dockerfile

I'm trying to use bosun with latest ElasticSearch 2.0.
I've changed Go version to 1.6 because I can't compile latest master :( 
Looks like `elastic.v3` uses Go 1.6.
```
cmd/bosun/expr/elastic.go:13:2: cannot find package "gopkg.in/olivere/elastic.v3" in any of:
/usr/local/go/src/gopkg.in/olivere/elastic.v3 (from $GOROOT)
/go/src/gopkg.in/olivere/elastic.v3 (from $GOPATH)
2016/02/20 22:20:40 exit status 1
exit status 1
```
Now looks like working
```
➜  docker git:(docker-0.5.0-alpha) docker run -d -p 4242:4242 -p 8070:8070 stackexchange/bosun
538abf33e180a14d4734b272a1b4824f28c8d2ec6e803617faaad4f36988990a
```
Also I see strange behavior with frontend. I understand that it's not so stable.
For smoke testing I'm using examples from https://bosun.org/quickstart
```
tsdbHost = localhost:4242 …
```

Fixed link and Go version

---

vsphere/vsphere.go

Escape soapLogin credentials

---

cmd/scollector/collectors/google_analytics.go
cmd/scollector/collectors/redis_linux.go

There may be a better way to do this, but we see the following error every time the collector runs:
Mar  4 00:25:57 ny-bosun01 scollector[23960]: error: interval.go:64: c_google_analytics:
@captncraig @alienth

cmd/scollector: fix error: interval.go:64: c_google_analytics:

---

cmd/bosun/expr/funcs.go

Check that we are not generating invalid tags in parseGraphiteResponse
because that would result in a crash if we try to create an Incident
with these tags.
I was able to reproduce the crash using this alert:
```
alert example.graphite {
template = generic
$graphite = graphite("sumSeries(constantLine(1),constantLine(2))", "5m", "", "")
warn = avg($graphite) > 1
}
panic: opentsdb: bad tag: constantLine(2))
goroutine 67 [running]:
panic(0xd70e60, 0xc8200e2610)
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
bosun.org/models.AlertKey.Group(0xc820846700, 0x40, 0xc820846700)
/Users/avereha/src/go/src/bosun.org/models/alertKey.go:46 +0x286
bosun.org/cmd/bosun/sched.NewIncident(0xc820846700, 0x40, 0xc82034dbc0)
/Users/avereha/src/go/src/bosun.org/cmd/bosun/sched/check.go:46 …
```

cmd/bosun/expr: fix crash on invalid graphite tags

---

cmd/bosun/expr/expr.go
cmd/bosun/expr/funcs.go
cmd/bosun/expr/parse/node.go
cmd/bosun/expr/parse/parse.go
cmd/bosun/expr/parse/parse_test.go
docs/expressions.md

Also fix nv() so it creates a result when the entire set is empty
```
$now = epoch()
$hourAgo =  $now-d("1h")
$s = merge(series("foo=bar", $hourAgo, 5, $now, 10), series("foo=bar2", $hourAgo, 6, $now, 11))
```

cmd/bosun: series func to create series from scalars

---

cmd/bosun/expr/expr.go
cmd/bosun/expr/expr_test.go
cmd/bosun/expr/funcs.go
cmd/bosun/expr/parse/node.go
docs/expressions.md

cmd/bosun: series operations

---

cmd/bosun/expr/funcs_test.go
opentsdb/duration.go

e.g. tod(4500) was evaluating as 75h instead of 75 minutes

tod(scalar) was returning minutes as hours

---

cmd/bosun/database/database.go
cmd/bosun/database/search_data.go
cmd/bosun/database/test/util/purge_search_data.go

Small utility to clean up search data for a metric.

---

docs/expressions.md

Correcting misspelling of Notificaiton where it appears in example code;
Corrected misspelling of Parition
Change a variable name in an example to remove any potential ambiguity caused by use of $q in proximity to a q() call.

docs: Fixing of typos and avoiding a potential ambiguity

---

cmd/bosun/sched/notify.go
cmd/bosun/sched/sched.go

cmd/bosun: stopping notifications that should no longer fire

---

docs/resources.md

- CLI tool to send single metric datum from shell scripts etc.

Adds resource reference to bosun_emitter

---

cmd/scollector/collectors/extrahop.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go
cmd/scollector/main.go
vendor/github.com/kylebrandt/gohop/gohop.go

Additional functionality into ExtraHop collector for specifying additional keyed metrics to be collected.
Also made some small formatting & comment changes to be in-line with Go standards.

cmd/scollector: Additional functionality into ExtraHop collector

---

cmd/bosun/database/error_data.go

https://github.com/bosun-monitor/bosun/issues/1753 maybe

cmd/bosun: add missing redis connection close

---

cmd/scollector/collectors/redis_counters.go

Currently switching on if `INFO server` contains `redis_version` to detect redis / ledis.

cmd/scollector: fixing redis counters collector to work with ledis or redis

---

docs/expressions.md

and clarify lookup()
lookupsSeries was implemented in https://github.com/bosun-monitor/bosun/pull/690
but not documented yet.
this one goes out to @kylebrandt . better late than never right?

document lookupSeries. fix #1035

---

cmd/scollector/collectors/google_analytics.go

:eyeglasses: @kylebrandt / @captncraig 
This is so we can keep an eye on referral traffic for SO.

Add trafficSource tracking for detailed GA metrics.

---

cmd/scollector/collectors/collectors.go
cmd/scollector/collectors/collectors_test.go
cmd/scollector/collectors/processes_linux.go
cmd/scollector/collectors/program.go
collect/queue.go
opentsdb/tsdb.go
opentsdb/tsdb_test.go

1. opentsdb.DataPoint.IsValid is largely unchanged. Determines if datapoint is valid to submit as is.
2. If collect gets a non-cleanable datapoint it silently drops it.
3. When you `Add` a datapoint, if the tags cannot be cleaned, it will log a message with (hopefully) a helpful line number, and drop it.

Not allowing invalid datapoints to ruin entire batches

---

cmd/bosun/sched/check.go

cmd/bosun: squelched keys don't go unknown.

---

opentsdb/tsdb.go
opentsdb/tsdb_test.go

The only problem I've found so far is that bosun cannot handle nan's from openTSDB, so that policy cannot be used yet. Closes #1707

Add support for fill policies when using opentsdb 2.2

---

cmd/scollector/collectors/cadvisor.go
cmd/scollector/collectors/google_analytics.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go
metadata/metadata.go

This PR modifies the cadvisor collector in 3 ways:
* container.cpu.system and container.cpu.user are grouped under container.cpu with the tag type=(user|system).
* cpu usage per cpu now optional via the [[Cadvisor]].PerCpuUsage config and moved to container.cpu.usage.percpu. What was container.cpu.usage cpu=all is now alone on that metric and we can have container.cpu.usage.percpu cpu=%d for each cpu. These are still generated for each container. On a system with a lot of CPUs and containers this generated too much data that was of little use.
* corrected metadata info: cpu times are in nanoseconds.

cmd/scollector: cadvisor collector cpu metrics review

---

cmd/scollector/collectors/cassandra_unix.go

Small bugfix on the nodetool cfstats output parsing. We can get this kind of output:
```
Keyspace: MyKeyspace
Read Count: 0
Read Latency: NaN ms.
Write Count: 11119269
Write Latency: 0.03063775793174893 ms.
Pending Flushes: 0
Table (index): MyKeyspace.my_idx
SSTable count: 3
Space used (live): 16584359
Space used (total): 16584359
...
```
As the collector currently is it will pass "MyKeyspace.my_idx" as a datapoint value which doesn't work so well. It then fails in the json encoder down the line since it's not a float nor an integer.

cmd/scollector: cassandra collector value validation

---

cmd/bosun/expr/expr.go
cmd/bosun/expr/funcs.go
cmd/bosun/expr/funcs_test.go
docs/expressions.md

There are a good amount of changes here so I will break them down here.
- Added new `NewSortableSeries` function. This allows you to convert a series into a sortable series but it doesn't do the sorting for you. This is useful if you want to use the comparison operators and hold onto state but you don't care about it being ordered from the onset.
- Added new `Tail` function to builtins. This function uses a very basic quickSelect to find the latest data points and returns just the final k data points. I will be adding additional documentation for this in the next commit. If there are less data points in the series than requested for by tail the series is left untouched.
- New unit test for the `tail` function and the `quickSelect` function are now part of the `funcs_test.go`
- New …

Bosun function tail

---

cmd/scollector/collectors/hp_eva_windows.go

Metrics:
> hp.eva.diskgroup.bytes
> hp.eva.diskgroup.latency
> hp.eva.diskgroup.ops
> hp.eva.diskgroup.queue
> hp.eva.hostconnection.queuedepth
> hp.eva.hostport.bytes
> hp.eva.hostport.latency
> hp.eva.hostport.ops
> hp.eva.hostport.queue
> hp.eva.storagearray.totalkb
> hp.eva.storagearray.totalrequests
> hp.eva.storagecontroller.cpu
> hp.eva.storagecontroller.transfer
> hp.eva.vdisk.bytes
> hp.eva.vdisk.latency
> hp.eva.vdisk.ops

scollector: HP Enterprise Virtual Array (EVA) statistics collector

---

snmp/snmp.go

Should prevent scollector to crash.

cmd/scollector: Fix snmp.go panic: runtime error: index out of range

---

util/command.go

Currently it looks like we send two interrupts ats the same time, and log one of them as a kill.

util: try interrupt, wait 2x, then kill

---

cmd/bosun/sched/views.go

Instead of using
`hasTags:host=host1 OR hasTags:host=host2`
this change allows the user to use just:
`hasTag:host=host1|host2`

allow filtering using syntax hasTags:host1|host2|host3

---

cmd/bosun/sched/host.go
cmd/bosun/search/search.go
cmd/bosun/web/search.go

this can be tested with the command:
curl -G 'http://bosun-host:8070/api/tagsets/os.net.bytes?since=1468592138' --data-urlencode 'tags=host=daileon'
"since" is an optional parameter and will default to retrieve all tags,
which is the previous behavior. Invalid timestamps will result in error.

let the user sets an expiry date for tags when using the http api

---

collect/queue.go

This is a minor optimization that should reduce gc pressure in the collect package.
Tested with a simple app that sends batches of 300 data points to a local black hole server every 30ms. Monitored with [expvarmon](https://github.com/divan/expvarmon)
super unscientific data:
Before:
After:
Notice difference in HeapAlloc and Alloc. gc time is pretty much negligible at this scale, but its always good to throw away less stuff.

collect: creating buffer pool for sending datapoints

---

opentsdb/tsdb.go
opentsdb/tsdb_test.go

Benchmarks:
Before:
```
BenchmarkReplace_Noop-8        	 1000000	      1865 ns/op	     592 B/op	      51 allocs/op
BenchmarkReplace_Something-8   	 1000000	      1442 ns/op	     336 B/op	      37 allocs/op
```
After:
```
BenchmarkReplace_Noop-8        	 5000000	       327 ns/op	       0 B/op	       0 allocs/op
BenchmarkReplace_Something-8   	 1000000	      1676 ns/op	     336 B/op	      37 allocs/op
```
Could potentially optimize the replacing case, especially since we are almost always reducing the size of the string, but I think this should relieve some of the allocs I saw.

opentsdb: minor optimization to Replace. No alloc on happy path.

---

cmd/scollector/collectors/hp_eva_windows.go

Went too far fixing go lint messages, should've fixed that before commit. This patch will make #1761 work correctly.
Also added error messages wrapping.

HP EVA: Fix WMI names

---

cmd/scollector/collectors/disk_linux.go

Rarely there are /dev/md* files but no mdadm installed.

cmd/scollector: skip md volumes if mdadm binary is missing

---

opentsdb/tsdb.go

Small edge case I ran into. ParseFloat() can succeed and return a NaN which then cannot be marshaled into json later on.

cmd/scollector: Check for NaN in Valid()

---

collect/collect.go
collect/queue.go
opentsdb/tsdb.go

- TagSet.Clean() validates cleaned key/value are not empty.
- DataPoint.Clean() is also called when quickly dequeuing the datapoint channel.
- Data points deemed unclean increment scollector.collect.discarded instead of scollector.collect.dropped.

cmd/scollector: bugfix - datapoint validation

---

cmd/scollector/collectors/collectors.go

The add function in cmd/scollector/collectors/collectors.go uses host= to indicate that tag should be omitted
See https://github.com/bosun-monitor/bosun/blob/ac7f667fa1e649b877b77bfab7f2a643f5d8e615/cmd/scollector/collectors/collectors.go#L292
This should fix the vsphere errors on ny-bosun01:
```
error: collectors.go:256: Invalid tagset discovered: {disk=CO-EQL,host=}. Skipping datapoint. Added from: vsphere.go:138
error: collectors.go:256: Invalid tagset discovered: {disk=datastore1,host=}. Skipping datapoint. Added from: vsphere.go:105
error: collectors.go:256: Invalid tagset discovered: {disk=datastore1,host=}. Skipping datapoint. Added from: vsphere.go:136
error: collectors.go:256: Invalid tagset discovered: {disk=datastore1,host=}. Skipping datapoint. Added from: vsphere.go:138
```

cmd/scollector: fix empty host= tags not working after PR #1856

---

cmd/scollector/collectors/collectors.go
cmd/scollector/collectors/processes_linux.go
cmd/scollector/collectors/processes_windows.go
cmd/scollector/main.go

This should help prevent memory leaks in CGO or WMI from causing scollector to consume too much memory.

cmd/scollector: add a kill switch for total memory used by scollector

---

cmd/bosun/docker/build/Dockerfile
cmd/tsdbrelay/main.go
metadata/metadata.go

Also:
removes runtime.GOMAXPROCS(runtime.NumCPU()) since that is now the default
tabs to spaces in docker.sh
updates docker image to use to go1.7.linux-amd64.tar.gz
fixes missing call to metadata.init
adds metrics for tracking errors from opentsdb/bosun
adds metrics for tracking relayed/errors from secondary relays.
~~This also changes the logic so that data points are always relayed to bosun and secondary relays instead of bailing when the primary opentsdb end point returns an error.~~ Will keep thinking on this and open a separate PR.
Fixes #1792

cmd/tsdbrelay: enable version numbers, fix metadata, add error metrics

---

cmd/scollector/collectors/dns_windows.go

Collector was trying to parse the pointed to TSDB instead of the value, which of course is kinda bad.
This _used_ to work and stopped early August. Not sure why it used to work? Maybe something in the WMI class changed. Haven't really dug into who it used to work and now doesn't.

cmd/scollector: Bug fix for DNS collector

---

cmd/bosun/database/config_data.go
cmd/bosun/database/database.go
cmd/bosun/database/error_data.go
cmd/bosun/database/metric_metadata.go
cmd/bosun/database/notification_data.go
cmd/bosun/database/search_data.go
cmd/bosun/database/silence_data.go
cmd/bosun/database/state_data.go
cmd/bosun/database/tag_metadata.go
cmd/bosun/database/test/testSetup.go

Uses some runtime magic to automatically track redis calls. Avoids the super ugly defer in every damn call.

Making redis monitoring a little prettier.

---

cmd/scollector/collectors/cadvisor.go

Stumbled on a typo in the cadvisor collector.

fix typo for container.fs.available

---

cmd/scollector/collectors/processes_linux.go
cmd/scollector/collectors/systemd_linux.go

This is to prevent WatchedProc from tracking PIDs which were once used, but now belong to other unrelated processes.

cmd/scollector: When WatchedProc processes die, clean them up.

---

cmd/scollector/collectors/collectors.go
cmd/scollector/collectors/processes_linux.go
cmd/scollector/collectors/processes_windows.go

As requested by @kylebrandt .
:eyeglasses: @gbrayut @captncraig

cmd/scollector: Track process PIDs.

---

opentsdb/duration.go

:eyeglasses: @captncraig  @kylebrandt 
Will be using this to read durations from a config file on a separate utility.

Have opentsdb.Duration implement encoding.TextUnmarshaler.

---

cmd/scollector/collectors/azureeabilling.go
vendor/github.com/mhenderson-so/azure-ea-billing/azure-ea-billing.go
vendor/vendor.json

Two bug fixes for Azure EA Billing:
1. Use HTTPS as the default protocol. This has been fixed upstream, so did a `vendor update` here
2. Don't return when we don't immediately find an appropriate month. I think this worked in the testing because the list was in the reverse order (so it would process two records and then stop), but the order is not reliable, obviously.

cmd/scollector: bug fixes for Azure EA billing

---

cmd/bosun/database/database.go
cmd/bosun/database/migrate.go
cmd/bosun/database/state_data.go
cmd/bosun/main.go
cmd/bosun/sched/check.go
cmd/bosun/sched/notify.go
cmd/bosun/sched/sched.go
cmd/bosun/sched/sched_test.go
cmd/bosun/web/expr.go
cmd/bosun/web/relay_test.go
cmd/bosun/web/web.go
models/incidents.go

Lots in these changes so need to rest and look at it with a fresh page of eyes.
Problem right now is that when expanding things on the dashboard, sometimes there are templates, and other times there are not.
The following seems not right:
```
$ redis-cli -p 6389 LRANGE allIncidents 0 -1 | wc -l
71077
$ redis-cli -p 6389 KEYS incidentById:\* | wc -l
64492
```
Also maybe something to do with not storing when emailbody == body? 
Anyways, need a break. The dashboard loads much faster though. Even with a handful of alerts the "Setup" phase in marshal groups goes down by a factor of 10 (30 vs 300ms)

wip: start to attempt to migrate rendered templates out of data structure

---

cmd/scollector/collectors/dsc_windows.go
cmd/scollector/conf/conf.go
cmd/scollector/conf/conf_darwin.go
cmd/scollector/conf/conf_linux.go
cmd/scollector/conf/conf_windows.go
cmd/scollector/main.go
cmd/scollector/service_windows.go
vendor/github.com/StackExchange/mof/node.go
vendor/github.com/StackExchange/mof/parse.go
vendor/github.com/StackExchange/wmi/LICENSE
vendor/github.com/StackExchange/wmi/README.md
vendor/github.com/StackExchange/wmi/swbemservices.go
vendor/github.com/StackExchange/wmi/wmi.go
vendor/vendor.json

This updates the WMI package to include the SWbemServices updates from https://github.com/StackExchange/wmi/pull/23
I plan on testing this in our environment to make sure things are stable. Shouldn't cause any issues as everything is behind the UseSWbemServicesClient = true value in scollector.toml

cmd/scollector: enable SWbemServices worker for better WMI performance in Windows

---

cmd/backfill/main.go
cmd/bosun/conf/notify.go
cmd/bosun/sched/template.go
cmd/scollector/collectors/elasticsearch.go
cmd/scollector/collectors/interval.go
collect/queue.go
metadata/metadata.go

After Jason updated tsdbrelay I did an audit of the various places we use Body.Close but don't read any bytes. This should allow connection reuse in those cases. Testing on ny-gbraylx01 but would like someone to review @captncraig @alienth @kylebrandt

misc: Drain body responses so that connection is eligible for reuse

---

cmd/tsdbrelay/doc.go
cmd/tsdbrelay/main.go

This is a first try at adding support for HTTPS in -t, -b, and -r parameters in tsdbrelay. I also rigged up the url fragment to allow filtering of what data gets sent to a relay. If you add `#data-only` or `#metadata-only` to the end of a host in the -r parameter section it should filter the relay results sent to that host. This is useful when the remote endpoint is NOT a load balancer or tsdbrelay instance, but instead a native OpenTSDB compatible endpoint
I haven't started testing yet, but let me know if there are any objections/recommended changes

cmd/tsdbrelay: parse -t -b and -r parameters as URLs and allow filtering of relay data

---

opentsdb/tsdb.go

Assumes if it overflows uint32, we are dealing with ms. Seems safe enough until 2106.

Clean millisecond timestamps

---

docs/expressions.md

The current expressions.md file contains hyperlinks to elastic.co that follow a deprecated uri pattern.  This PR amends those links to go to 2.4 reference documentation instead of 2.x

fix elastic links to go to 2.4 instead of 2.x

---

cmd/scollector/collectors/collectors.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go

Prepend every metrics with a custom prefix set in the toml configuration file.

Add support for metric prefix

---

docs/resources.md

_rs-collector_ is a [Bosun](https://bosun.org) compatible collector for various services that are not covered by [scollector](https://bosun.org/scollector/), and that we use at [CenterDevice](https://www.centerdevice.de/en/).

Add rs-collector to resources web page

---

cmd/scollector/collectors/elasticsearch.go

Elastic 5.x route of `/_nodes/_local/stats` emits a single IP address,
such as
```
"ip": "10.7.1.74:9300"
````
However prior to v5 this is an array:
```
"ip": [
"10.7.1.74:9300"
],
```
We do not use the IP address attribute from this route anywhere in the
collector, so removing it from the JSON decoding stops the error, and has no
impact on the collectors functionality (apart from making it work again).

cmd/scollector: Fixed bug in ElasticSearch collector for Elastic 5.x

---

cmd/scollector/collectors/azureeabilling.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go
cmd/scollector/main.go

Also converted to better invocation style.

cmd/scollector: Updated Azure EA collector to add new tags.

---

cmd/scollector/collectors/awsBilling.go

The billing collector did not correctly account for Route 53 zone billing
where the bill contains an empty zone name.
This fixes issue #2147

cmd/scollector: Fix bug in AWS billing collector.

---

cmd/scollector/main.go

Upon startup, scollector reports which OpenTSDB host it is connected to.
In case there is authentication required, the credentials were logged as
part of the URL. This patch replaces them with dummies.

cmd/scollector: Hide TSDB credentials in logs

---

cmd/bosun/conf/system.go
cmd/bosun/web/middlewares.go
vendor/github.com/captncraig/easyauth/providers/ldap/ldap.go
vendor/vendor.json

support for LDAP user authentication.

---

cmd/bosun/conf/notify.go

This will add alert key and notification name to  HTTP notification failure log.
Current failure log:
```
2017/11/21 14:15:41 error: notify.go:48: sending http: bad response on notification POST: 400
```
With this change:
```
2017/11/28 15:17:18 error: notify.go:48: sending http: bad response on notification with name bosun_uptime for alert bosun_uptime{} method POST: 400
```

Fix post notification logging

---

cmd/bosun/conf/rule/rule.go

Load `macros` before notifications, so that we can able use it in notifications which will reduce the duplications.
https://github.com/bosun-monitor/bosun/issues/2194

Fix macros for Notifications

---

cmd/bosun/bosun.example.toml
cmd/bosun/conf/system.go
cmd/bosun/conf/system_test.go

This change closes https://github.com/bosun-monitor/bosun/issues/2195

Add Scheme option to bosun toml

---

cmd/bosun/conf/rule/loaders.go

Bosun complaining about `actionBodyForceClose`, `actionBodyDelayedClose`, and `actionBodyCancelClose` intermediately and causing crash with error `couldn't read rules: unknown key actionBodyDelayedClose` after looking at the code cmd/bosun/conf/rule/loaders.go#L442 we found strings.HasSuffix sometime getting matched with 'Close' rather then 'DelayedClose, ForceClose or CancelClose' and later it breaks in the switch statement cmd/bosun/conf/rule/loaders.go#L462 due to invalid template type
Debug log:
```
2017/11/29 11:27:26 enabling syslog
2017/11/29 11:27:26 info: loaders.go:439: Key was: actionBodyDelayedClose
2017/11/29 11:27:26 info: loaders.go:442: Key after trim action: BodyDelayedClose
2017/11/29 11:27:26 info: loaders.go:448: ActionType: Closed
2017/11/29 11:27:26 info: …
```

Bosun complaining about `actionBodyForceClose`, `actionBodyDelayedClo` and `actionBodyCancelClose`

---

cmd/bosun/sched/views.go
docs/usage.md

Hi,
We often have difficulties to filter out alerts which are in given status (e.g. normal) older than given time (e.g. 1d or 1h).  This new filter will allow us to filter alert with last update time, same as `Current Status since` displayed in the incident page.
e.g. `status:normal AND since:<15d` will display alerts that are in `normal` since 15day's or more.
Thanks,

Added a incident filter called "since"

---

cmd/bosun/conf/notify.go
cmd/bosun/web/web.go
collect/collect.go
docs/api.md

Currently, bosun collects a bunch of runtime debug and performance stats and write it back to OpenTSDB. This endpoint will expose these stats,  useful when you are not using Bosun with OpenTSDB.
At present, the endpoint only exposes `notification` success and failure stats but we can add any other stats in future if required.
Thanks,

Added new api endpoint /api/debug/{key}

---

cmd/scollector/collectors/ifstat_linux.go

Add systemd predictable network interface names into linux network name regex. The systemd mention of these prefixes exists here: https://github.com/systemd/systemd/blob/master/src/udev/udev-builtin-net_id.c#L29
This adds `ww`, `wl`, and `en` to the possible prefixes for interface names and also changes the space up front to be optional. When the names get too long for the column, I have noticed that the text aligns to the start of the line instead of the colon.
This should fix issues others have been having with network interfaces not showing up. 
Related:
https://github.com/bosun-monitor/bosun/pull/1756
https://github.com/bosun-monitor/bosun/issues/1912

cmd/scollector: Update linux interface collector names.

---

cmd/bosun/conf/notify.go

We have noticed when a post action notification triggered bosun also trying to send mail with empty 'To' address
`2018/02/05 12:15:30 error: notify.go:49: sending email: Must specify at least one From address and one To address
`
`
2018/02/05 12:17:30 error: notify.go:205: failed to send alert  to [] Must specify at least one From address and one To address`
This patch will validate the 'To' address slice length and stop trying sending mail if it's empty
Thanks,

Stop sending mail if 'To' slice empty

---

cmd/bosun/conf/actionNotify.go
cmd/bosun/conf/notify.go
cmd/bosun/conf/unknownNotify.go

This is follow up to our last PR #2196, we still having difficulties to trace notifications failures due to missing alert key's for action and unknown notifications e.g. mentioned below is an error sample we are getting more often  
`2018/02/08 16:31:44 error: notify.go:55: sending http: bad response on notification with name memcached_pagerduty for alert  method POST: 400`
As you can see it's very difficult to find out details like for which alert it's failing and either it's an action notification or an unknown etc, with this change we will be able to get more details e.g 
`2018/02/09 15:28:06 error: notify.go:56: sending http: bad response for 'memcached_pagerduty' unknown notification using template key '' for alert keys memcached_memory_usage{host=XXXXXXX} method POST: 400`
With …

Fix notifications log

---

cmd/bosun/expr/influx.go

Follow up to #2234
Sorry, you've merged it so fast : )

Print `db` as well, when profiling InfluxDB queries

---

cmd/bosun/conf/system_elastic2.go
cmd/bosun/conf/system_elastic5.go

This patch will fix the ES cluster config maps by moving the `addClientOptions` and `esConf` inside the for loop
- conf/system_elastic2.go :-  moved `addClientOptions` and `esConf` inside the for loop
- conf/system_elastic5.go :-  moved `addClientOptions` and `esConf` inside the for loop
Thanks,

We have noticed sometimes ES config maps are getting conflicts when using multiple ES cluster with client options enable.

---

docs/definitions.md

Presumably as part of the PR #2135 three new global template functions
were added: json, makeSlice, and makeMap. However they are not mentioned
nor documented at http://bosun.org/definitions. This commit attempts to
fill in the gap.

docs: Document json, makeSlice, and makeMap template functions

---

cmd/bosun/sched/views.go

If we use **... AND (user:*)** filter in incident-filter - nothing return...
So, this this small patch fixes it and filter begin work like it written in  [help](https://bosun.org/usage#incident-filters)

fix user filter

---

opentsdb/tsdb.go
opentsdb/tsdb_test.go

opentsdb/tsdb:      Fix parsing of 2.2+ filters so that only group terms get added to the result tag set
opentsdb/test_test: Add test cases to validate that the result tag set is being correctly populated

fixes 2211

---

cmd/scollector/collectors/elasticsearch.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go

cmd/scollector: Added Elastic config options

---

cmd/bosun/README.md

This is just to reduce confusion for people starting out with Bosun.

Update README to refer to bosun.toml instead of outdated conf file

---

cmd/bosun/expr/expr.go
cmd/bosun/expr/funcs.go
cmd/bosun/expr/funcs_test.go
docs/expressions.md

This PR adds an `aggregate` DSL function, which allows one to combine different series in a seriesSet using a specified aggregator (currently `min`, `max`, `p50`, `avg`). 
This is particularly useful when comparing data across different weeks (using the `over`) function. In our case, for anomaly detection, we want to compare the current day's data with an aggregated view of the same day in previous weeks. In particular, we want to compare each point in the last day to the _median_ of each point in the corresponding day for the last 3 weeks, so that any anomalies that occurred in a previous week are ignored. This way we compare with a hypothetical "perfect" day.
For example:
```
$weeks = over("avg:10m-avg-zero:os.cpu", "24h", "1w", 3)
$a = aggregate($weeks, "", "p50")
merge($a, $q)
``` …

Add series aggregation DSL function `aggregate`

---

docs/expressions.md

This PR adds some more detailed documentation about the aggr function, in particular focusing on error conditions and that timestamps need to be aligned.
@kylebrandt what do you think, is this clear enough?

Add more detailed documentation on the potential pitfalls of aggr

---

cmd/bosun/conf/conf.go
cmd/bosun/conf/system.go
cmd/bosun/sched/alertRunner.go
docs/system_configuration.md

This is a solution for #2065 
The idea behind this is simple. Every check run is slightly shifted so that the checks are distributed uniformly. 
For the subset of checks that run with the period `T`, a shift is added to every check. The shift ranges from `0` to `T-1`. The shifts are incremental. For example, if we have 6 checks every 5 mins (`T=5`). The shifts will be ` 0`, `1`, `2`, `3`, `4`, `0`. This way, without the patch 6 checks will happen at times `0`, and `5`; with the patch, two checks will happen at the time `0`, one at `1`, one at `2`, and so on. The total number of checks and check period stay the same.
Here is the test that shows the effect of the patch on system load. Note, that the majority of checks in this system have 5 mins period.

Distributed alert checks to prevent high load spikes

---

cmd/bosun/expr/expr_test.go
cmd/bosun/expr/funcs.go
cmd/bosun/expr/funcs_test.go

This PR fixes a bug in `aggr` that causes math operations on the resulting series to fail. It also adds tests for such cases, and refactors the `aggr` tests to be [table-driven](https://github.com/golang/go/wiki/TableDrivenTests).
Without this fix, math operations cause an error like expr: opentsdb: bad tag: color. The tests included here were failing before the fix with such an error.
CC @kylebrandt

Fix math operations on results of aggr

---

cmd/scollector/collectors/elasticsearch.go
cmd/scollector/collectors/interval.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go

Adds new configuration options for Elastic, allowing to establish encrypted (https) connections, and providing HTTP basic auth credentials.
Also adds a convenience flag to easily disable an Elastic block without actually having to remove it.

Allow Elasticsearch Auth and TLS

---

cmd/bosun/conf/unknownNotify.go
cmd/bosun/sched/notify.go
docs/definitions.md

Currently, we have a very limited number of variable available to the unknown templates which prevent us to match the alert and action notification template (includes incident states) and sometimes unknowns are getting unnoticed due inconsistency (when using external notification systems e.g. pagerduty).
With this patch, I tried to include the alert states to unknown which is very useful when grouping disable using [unknownMinGroupSize](http://bosun.org/definitions#unknownmingroupsize).
Please let me know your thoughts.

Added extra info to unknown templates

---

cmd/bosun/expr/expr_test.go
cmd/bosun/expr/tsdb.go
docs/expressions.md

This PR adds two functions for querying against openTSDB – `overQuery` and `bandQuery`. These functions slightly generalise the existing `over` and `band` functions to include an end duration parameter `eduration`, which specifies when a query should end, as is done with `q`. This enables queries for a historical distribution that does not include recent outliers – related discussion in #2297 .
The existing `over` and `band` functions are changed to wrap the more general functions. The undocumented and very related `shiftBand` function was found during this work, and is added to the documentation.
The third commit f61259a refactors the functions to reuse `bandTSDB`, as `shiftBand` used this function to achieve comparable functionality to `over`.
Tests were written based on the existing …

Add tsdb query functions with end duration parameter.

---

cmd/bosun/conf/actionNotify.go
cmd/bosun/conf/notify.go
cmd/bosun/conf/unknownNotify.go
cmd/bosun/web/web.go

Sometimes people would complain that notifications about close/ack were not delivered to them
it seems that it's not possible to easily debug that now with current state of logs.
There is no log entries about successfull sending acks and closes. Only log failures (e.g. 400 response)
- notifications option 'print = true' also seems to not do anything for action notifications (even for failed notifications that are logged)
- logs don't allow you to understand if 'Send notifications' checkbox was on or off
- log successful actions (similar to how it logs alert notifications)
- print new logs according to 'notification' settings
- improve error log format - write extra data about notification that has delivery problem
- log actions if there wasn't set checkbox notification
- add logging if …

Improve logs

---

build/build.go
build/validate.sh

no longer needed with multiple es version support

build: remove esv5 argument

---

cmd/bosun/expr/expr.go
cmd/bosun/expr/expr_test.go
cmd/bosun/expr/funcs_test.go
cmd/bosun/expr/map_test.go
cmd/bosun/sched/check.go
cmd/bosun/sched/template.go
cmd/bosun/web/chart.go
cmd/bosun/web/expr.go

this way when we attempt to recover or panic we can identify the source of the issue

cmd/bosun: add origin to expr state

---

cmd/bosun/expr/influx.go

Fixes a tcp session leak by calling Close() on the influxdb client connection before exiting.
Our InfluxDB was crashing and having issues on an older version, and then bosun was getting back invalid Influx result errors even though other programs could query it.  Upon investigation it was discovered we had over 39,000 connections to the InfluxDB instance running on localhost from bosun and no new connections could be made.
The influxdb client close method properly frees these sessions after a query and connection counts are below 30 now.

Cleanup influxdb http client connection resources

---

cmd/bosun/docker/build/Dockerfile

The Bosun compilation by running [`bosun/cmd/bosun/docker/docker.sh`](https://github.com/bosun-monitor/bosun/blob/03ad93d1efaf9a14d95f9a8da7e9cf08974ae67c/cmd/bosun/docker/docker.sh) currently fails:
```
> ./docker.sh
> ...
> Step 14/14 : RUN go run build/build.go     && bosun -version     && scollector -version     && tsdbrelay -version
> building bosun
> go install -ldflags -X bosun.org/_version.VersionSHA=03ad93d1efaf9a14d95f9a8da7e9cf08974ae67c -X bosun.org/_version.VersionDate=20181215204533 bosun.org/cmd/bosun
cmd/bosun/database/migrate.go:109: undefined: sort.Slice
2018/12/15 20:46:33 exit status 2
exit status 1
```
This happens because the build is using `go1.7`, while `sort.Slice` was introduced in `1.8`, see https://golang.org/pkg/sort/#Slice
This commit contains the `golang` …

Upgraded go version in the Dockerfile for bosun build

---

cmd/scollector/collectors/haproxy_unix.go
cmd/scollector/conf/conf.go
cmd/scollector/doc.go

Adds support for instance-specific haproxy user/password pairs.
If specified at the HAProxy.Instance level, username/password
override those provided at the HAProxy level.

cmd/scollector: haproxy user/password per instance

---

cmd/bosun/expr/parse/node.go

Want  to make a test to show this problem before merging, but before something like the following would incorrectly error:
```
$q = ["default,it"]promm("up", "job,instance", "", "max", "30s", "4h", "")
$status = max($q)
$transposed = t($status, "bosun_prefix")
$sum = sum($transposed)
$sum - $sum
```

cmd/bosun: (wip) fix tags calculation on prefix nodes

---

cmd/bosun/expr/prom.go
docs/expressions.md

Example:
```
$step = 1m
promras(''' sum(rate(container_fs_reads_total[$step]) + rate(container_fs_writes_total[$step])) by (namespace) ''', "2m", "2h", "")
```
top level expression must be an aggregation operation with `by ()`.
Todo:
Follow up from conversation with @pdf in https://github.com/bosun-monitor/bosun/pull/2366

cmd/bosun: (wip) raw promql query support

---

cmd/bosun/web/web.go

When trying to get a pprof profile of the bosun server, I discovered that the path to `/debug/pprof` was being redirected back to the homepage of our bosun instance.
[Apparently](https://stackoverflow.com/questions/19591065/profiling-go-web-application-built-with-gorillas-mux-with-net-http-pprof) the `gorilla/mux` web framework clobbers the path to pprof, so this line of code allows the `http.DefaultServeMux` to handle the url at `/debug/pprof`, and opens the bosun server back up for profiling.

cmd/bosun/web: use DefaultServeMux for /debug/pprof requests

---

cmd/bosun/conf/conf.go
cmd/bosun/conf/system.go
cmd/bosun/database/database.go
cmd/bosun/database/sentinel/sentinel.go
cmd/bosun/database/test/testSetup.go
cmd/bosun/database/test/util/purge_search_data.go
cmd/bosun/main.go
docs/system_configuration.md

Currently we can have only one redis server. If we want to have some HA for bosun redis only way that we have HAProxy. But it require another service installation. So support of sentinels will allow us to have HA for redis without any extra services.
Added 2 new options - `RedisSentinels` (array), `RedisMasterName`. If `RedisMasterName` was set we try to connect to redis sentinels (`RedisSentinels` option) for receive current redis master.

Redis sentinel support for bosun

---

docs/examples.md

Just noticed this looking funny at https://bosun.org/examples#conditional-alerts

docs: fix markdown heading in examples.md

---

cmd/bosun/expr/funcs.go
cmd/bosun/expr/funcs_test.go

Fix panic in timedelta expression if series are empty
Fixes #2467

Fix panic in timedelta expression if series are empty

---

cmd/bosun/main.go
cmd/scollector/main.go
cmd/tsdbrelay/main.go
util/util.go

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like
---
Fixes a bug that was introduced with #2439 which now requires the
initialisation of the HostManager on startup. That was forgotten to add
to the tsdbrelay command, causing it to panic on startup.
Fixes: #2475
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration

Initialise host manager when starting tsdbrelay

---

.github/workflows/ci.yaml
.github/workflows/sonarcloud.yml
.gitignore
Makefile
sonar-project.properties

Add targets for generating coverage reports. Initial version of sonar config to exclude tests and vendored packages
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like
---
Add two features.
Short cut for generating and viewing coverage reports by running `make coverage`
Added step to generate coverage report as part of checks for use by sonarcloud
Makefile steps verified locally
- [x ] This contribution follows the project's [code of conduct](https://github.com/bosun-monitor/bosun/blob/master/CODE_OF_CONDUCT.md)

Add test coverage report generation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md

Wraps the help text into comments so that they are still visible to
contributors, but won't show up on the PR itself.
Example for the PR template:

Update Github templates

---

cloudwatch/cloudwatch.go
cloudwatch/cloudwatch_test.go
cmd/bosun/bosun.example.toml
cmd/bosun/conf/conf.go
cmd/bosun/conf/rule/rule.go
cmd/bosun/conf/system.go
cmd/bosun/conf/system_test.go
cmd/bosun/expr/cloudwatch.go
cmd/bosun/expr/cloudwatch_test.go
cmd/bosun/expr/expr.go
cmd/bosun/sched/check.go
cmd/bosun/web/chart.go
cmd/bosun/web/expr.go
docs/expressions.md
docs/system_configuration.md
go.mod
go.sum

---
Replaces PR  #2262 . 
Internal version of this functionality had diverged sufficiently from original PR that it is cleaner to start afresh
Requires a role with the ListMetrics and GetMetricData capabilities.
Role can be supplied using either the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables or by attaching it to the EC2 instance on which bosun runs.

Adds support for directly querying cloudwatch metrics via the AWS SDK

---

_version/version.go
build/release.sh

Fix the release script.
OSX toolchain no longer supports building 386 binaries, so the darwin/386 combination throws an error
https://support.apple.com/en-us/HT208436
---
Update the version number in preparation for cutting new release
Fix an issue where the release.sh script will not complete because apple have removed 
Darwin 386 support from the toolchain
https://developer.apple.com/documentation/xcode-release-notes/xcode-10-release-notes?preferredLanguage=occ
Works towards #2230  (fill in)
- [] I have made corresponding changes to the documentation

Update the release version in preparation for 0.9.0-preview

---

docs/expressions.md

---
Fixes the documentation which described the behaviour of `dropbool`
incorrectly.
`dropbool()` currently drops the values where the value in the second
series set IS zero instead of, as described, dropping those where the
value IS NOT zero. To avoid a breaking change which would give the
function the more intuitive behaviour from its name, this only updates
the documentation.
We should consider fixing this with a breaking change in a future
release.
Fixes #2496
- Query `dropbool(series("foo=bar", 0, 1, 1, 1, 2, 1, 3, 1), series("", 0, 1, 1, 2, 2, 3, 3, 2) != 2)` returns `{"0": 1, "2": 1}`
- Query `dropbool(series("foo=bar", 0, 1, 1, 1, 2, 1, 3, 1), series("", 0, 1, 1, 2, 2, 3, 3, 2))` returns `{"1": 1, "2": 1, "3": 1}`
The behaviour is the inverse of the previously described behaviour. …

Update the documentation for dropbool
